/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import javax.swing.JOptionPane;
import br.aiec.projetoFinal.conexao.ModuloConexao;
import br.aiec.projetoFinal.modelo.ModeloCategoria;
import br.aiec.projetoFinal.controle.ControleCategoria;
import br.aiec.projetoFinal.modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;


/**
 *
 * @author Zangui
 */
public class FrmCategorias extends javax.swing.JFrame {
    ModuloConexao conex = new ModuloConexao();
    ModuloConexao conexTb = new ModuloConexao();
    ModeloCategoria cat = new ModeloCategoria();
    ControleCategoria controle = new ControleCategoria();
    
    int opcControl = 0;
    /**
     * Creates new form FrmCategorias
     */
    public FrmCategorias() {
        initComponents();
        preencheTabela("SELECT * FROM categorias ORDER BY catId DESC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCadCategoriaNovo = new javax.swing.JButton();
        btnCadCategoriaSalvar = new javax.swing.JButton();
        btnCadCategoriaEditar = new javax.swing.JButton();
        btnCadCategoriaCancelar = new javax.swing.JButton();
        btnCadCategoriaExcluir = new javax.swing.JButton();
        txtCadCategoriaId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtCadCategoriaNome = new javax.swing.JTextField();
        lblCadUsuarioNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadCategoriaNotas = new javax.swing.JTextArea();
        lblCadUsuarioNotas = new javax.swing.JLabel();
        lblCategoriaStatus = new javax.swing.JLabel();
        txtCategoriaStatus = new javax.swing.JTextField();
        lblCatNaoActivo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelCadUserPesquisar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCadCategoriaPesquisar = new javax.swing.JTextField();
        btnCadCategoriaPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCategoriaResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Categorias");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_categorias_20x.png"))); // NOI18N

        lblLogoName.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblLogoName.setText("GESTARQ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("- Categorias");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(816, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoName)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5))
        );

        btnCadCategoriaNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadCategoriaNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_novo_20x.png"))); // NOI18N
        btnCadCategoriaNovo.setText("Novo");
        btnCadCategoriaNovo.setToolTipText("Criar Novo Registo");
        btnCadCategoriaNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadCategoriaNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadCategoriaNovo.setIconTextGap(10);
        btnCadCategoriaNovo.setMaximumSize(new java.awt.Dimension(91, 35));
        btnCadCategoriaNovo.setMinimumSize(new java.awt.Dimension(91, 35));
        btnCadCategoriaNovo.setPreferredSize(new java.awt.Dimension(91, 35));
        btnCadCategoriaNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCategoriaNovoActionPerformed(evt);
            }
        });

        btnCadCategoriaSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadCategoriaSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_salvar_20x.png"))); // NOI18N
        btnCadCategoriaSalvar.setText("Salvar");
        btnCadCategoriaSalvar.setToolTipText("Salvar alterações");
        btnCadCategoriaSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadCategoriaSalvar.setEnabled(false);
        btnCadCategoriaSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadCategoriaSalvar.setIconTextGap(10);
        btnCadCategoriaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCategoriaSalvarActionPerformed(evt);
            }
        });

        btnCadCategoriaEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_actualizar_20x.png"))); // NOI18N
        btnCadCategoriaEditar.setText("Editar");
        btnCadCategoriaEditar.setToolTipText("Editar Registo");
        btnCadCategoriaEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadCategoriaEditar.setEnabled(false);
        btnCadCategoriaEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadCategoriaEditar.setIconTextGap(10);
        btnCadCategoriaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCategoriaEditarActionPerformed(evt);
            }
        });

        btnCadCategoriaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_cancelar_20x.png"))); // NOI18N
        btnCadCategoriaCancelar.setText("Cancelar");
        btnCadCategoriaCancelar.setToolTipText("Cancelar Operação");
        btnCadCategoriaCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadCategoriaCancelar.setEnabled(false);
        btnCadCategoriaCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadCategoriaCancelar.setIconTextGap(10);
        btnCadCategoriaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCategoriaCancelarActionPerformed(evt);
            }
        });

        btnCadCategoriaExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_excluir_20x.png"))); // NOI18N
        btnCadCategoriaExcluir.setText("Excluir");
        btnCadCategoriaExcluir.setToolTipText("Excluir Registo");
        btnCadCategoriaExcluir.setEnabled(false);
        btnCadCategoriaExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadCategoriaExcluir.setIconTextGap(10);
        btnCadCategoriaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCategoriaExcluirActionPerformed(evt);
            }
        });

        txtCadCategoriaId.setEnabled(false);
        txtCadCategoriaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCategoriaIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadCategoriaNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadCategoriaSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadCategoriaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(btnCadCategoriaCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadCategoriaExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtCadCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadCategoriaNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadCategoriaSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadCategoriaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadCategoriaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadCategoriaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCadCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtCadCategoriaNome.setBackground(new java.awt.Color(204, 204, 204));
        txtCadCategoriaNome.setEnabled(false);

        lblCadUsuarioNome.setText("Nome *");

        txtCadCategoriaNotas.setBackground(new java.awt.Color(204, 204, 204));
        txtCadCategoriaNotas.setLineWrap(true);
        txtCadCategoriaNotas.setRows(5);
        txtCadCategoriaNotas.setEnabled(false);
        jScrollPane1.setViewportView(txtCadCategoriaNotas);

        lblCadUsuarioNotas.setText("Informação adicional");

        lblCategoriaStatus.setText("Status");

        txtCategoriaStatus.setEnabled(false);

        lblCatNaoActivo.setText("Inactivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadUsuarioNome)
                    .addComponent(txtCadCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoriaStatus)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCatNaoActivo)
                        .addGap(8, 8, 8)
                        .addComponent(txtCategoriaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(lblCadUsuarioNotas, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCadUsuarioNotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCadUsuarioNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadCategoriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCategoriaStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCatNaoActivo)
                            .addComponent(txtCategoriaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setText("* Campos obrigatórios");

        panelCadUserPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Pesquisar Usuários");

        txtCadCategoriaPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        txtCadCategoriaPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadCategoriaPesquisarKeyReleased(evt);
            }
        });

        btnCadCategoriaPesquisar.setText("Pesquisar");
        btnCadCategoriaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCategoriaPesquisarActionPerformed(evt);
            }
        });

        jTableCategoriaResult.setBackground(new java.awt.Color(204, 204, 204));
        jTableCategoriaResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCategoriaResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCategoriaResultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCategoriaResult);

        javax.swing.GroupLayout panelCadUserPesquisarLayout = new javax.swing.GroupLayout(panelCadUserPesquisar);
        panelCadUserPesquisar.setLayout(panelCadUserPesquisarLayout);
        panelCadUserPesquisarLayout.setHorizontalGroup(
            panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                        .addComponent(txtCadCategoriaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadCategoriaPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCadUserPesquisarLayout.setVerticalGroup(
            panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadCategoriaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadCategoriaPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCadUserPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(panelCadUserPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 79, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1025, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCategoriaNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCategoriaNovoActionPerformed
        //Ao clicar no botão Novo, desbloqueia os campos inativos
        opcControl = 1;
        txtCadCategoriaNome.setEnabled(true);
        txtCadCategoriaNotas.setEnabled(true);
        btnCadCategoriaSalvar.setEnabled(true);
        btnCadCategoriaCancelar.setEnabled(true);
        btnCadCategoriaEditar.setEnabled(false);
        txtCadCategoriaNome.setText("");
        txtCadCategoriaNotas.setText("");
    }//GEN-LAST:event_btnCadCategoriaNovoActionPerformed

    private void btnCadCategoriaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCategoriaSalvarActionPerformed
        cat.setNome(txtCadCategoriaNome.getText());
        cat.setNotas(txtCadCategoriaNotas.getText());
        cat.setStatus(Integer.parseInt(txtCategoriaStatus.getText()));

        //Certifica que os campos obrigatórios não estão vazios
        if(txtCadCategoriaNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome para prosseguir");
            txtCadCategoriaNome.requestFocus();
        }else{
            if(opcControl == 1){
                //Grava efectivamente os dados no banco
                controle.gravarCategoria(cat);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT * FROM categorias ORDER BY catId DESC");
            }else{
                cat.setId(Integer.parseInt(txtCadCategoriaId.getText()));
                controle.editarCategoria(cat);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT * FROM categorias ORDER BY catId DESC");
            }
            //Após gravar limpa os campos para a próxima inserçao
            txtCadCategoriaNome.setText("");
            txtCadCategoriaNotas.setText("");

            //Torna os campos inativos novamente
            txtCadCategoriaNome.setEnabled(false);
            txtCadCategoriaNotas.setEnabled(false);
            btnCadCategoriaSalvar.setEnabled(false);
            btnCadCategoriaCancelar.setEnabled(false);
        }
    }//GEN-LAST:event_btnCadCategoriaSalvarActionPerformed

    private void btnCadCategoriaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCategoriaEditarActionPerformed
        // Habilita dos campos bloqueados
        opcControl = 2;
        txtCadCategoriaNome.setEnabled(!false);
        txtCadCategoriaNotas.setEnabled(!false);
        btnCadCategoriaSalvar.setEnabled(!false);
        btnCadCategoriaCancelar.setEnabled(true);
        btnCadCategoriaEditar.setEnabled(false);
    }//GEN-LAST:event_btnCadCategoriaEditarActionPerformed

    private void btnCadCategoriaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCategoriaCancelarActionPerformed
        // Cancelar 
        txtCadCategoriaNome.setEnabled(!true);
        txtCadCategoriaNotas.setEnabled(!true);
        btnCadCategoriaSalvar.setEnabled(!true);
        btnCadCategoriaCancelar.setEnabled(!true);
        btnCadCategoriaNovo.setEnabled(true);

        //Após cancelar limpa os campos para a próxima inserçao
        txtCadCategoriaNome.setText("");
        txtCadCategoriaNotas.setText("");
    }//GEN-LAST:event_btnCadCategoriaCancelarActionPerformed

    private void btnCadCategoriaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCategoriaExcluirActionPerformed
        // Exclui uma categoria
        int alerta = 0;
        alerta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir esta Categoria?");
        if(alerta == JOptionPane.YES_OPTION){
            cat.setId(Integer.parseInt(txtCadCategoriaId.getText()));
            controle.eliminarCategoria(cat);
        }
        //Após eliminar limpa os campos do formulário
        txtCadCategoriaId.setText("");
        txtCadCategoriaNome.setText("");
        txtCadCategoriaNotas.setText("");
        txtCadCategoriaPesquisar.setText("");
        //Habilita/desbilita alguns botões
        btnCadCategoriaNovo.setEnabled(true);
        btnCadCategoriaEditar.setEnabled(false);
        btnCadCategoriaExcluir.setEnabled(false);
        //Actualiza a tabela que lista os usuarios cadastrados
        preencheTabela("SELECT * FROM categorias ORDER BY catId DESC");
    }//GEN-LAST:event_btnCadCategoriaExcluirActionPerformed

    private void txtCadCategoriaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCategoriaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadCategoriaIdActionPerformed

    private void txtCadCategoriaPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadCategoriaPesquisarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCadCategoriaPesquisarKeyReleased

    private void btnCadCategoriaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCategoriaPesquisarActionPerformed
        // Pesquisa usuários cadastrados no BD
        int stt = 1;
        cat.setPesquisar(txtCadCategoriaPesquisar.getText());
        ModeloCategoria categ = controle.pesquisaCategoria(cat);
        txtCadCategoriaId.setText(String.valueOf(categ.getId()));
        txtCadCategoriaNome.setText(categ.getNome());
        txtCadCategoriaNotas.setText(categ.getNotas());
        txtCategoriaStatus.setText(String.valueOf(categ.getStatus()));
        
        if(txtCategoriaStatus.getText().equals(stt)){
            lblCatNaoActivo.setVisible(true);
        }else{
            lblCatNaoActivo.setVisible(!true);
        }
        
        //Desabilita botões
        btnCadCategoriaNovo.setEnabled(!false);
        btnCadCategoriaEditar.setEnabled(true);
        btnCadCategoriaExcluir.setEnabled(true);
    }//GEN-LAST:event_btnCadCategoriaPesquisarActionPerformed

    private void jTableCategoriaResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCategoriaResultMouseClicked
        // Ao seleccionar um item na tabela redireciona para o registo correspondente
        int stt = 1;
        String category = ""+jTableCategoriaResult.getValueAt(jTableCategoriaResult.getSelectedRow(), 1);
        conexTb.conexao();
        conexTb.executaSQL("SELECT * FROM categorias WHERE catNome ='"+category+"'");
        try {
            conexTb.res.first();
            txtCadCategoriaId.setText(String.valueOf(conexTb.res.getInt("catId")));
            txtCadCategoriaNome.setText(conexTb.res.getString("catNome"));
            txtCadCategoriaNotas.setText(conexTb.res.getString("catDesc"));
            //txtCategoriaStatus.setText(String.valueOf(conexTb.res.getInt("catStatus")));
            lblCatNaoActivo.setVisible(true);
    if(txtCategoriaStatus.getText().equals(stt)){
            txtCategoriaStatus.setText("Categoria activa");
        }else{
            
        }        
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: Não foi possível listar categorias \n"+ex.getMessage());
        }
        conexTb.desconetar();
        btnCadCategoriaEditar.setEnabled(true);
        btnCadCategoriaExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableCategoriaResultMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblCatNaoActivo.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    //Método para preencher a tabela resultado da pesquisa
    public void preencheTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Notas","Status"};
        conex.conexao();
        conex.executaSQL(Sql);
        try {
            conex.res.first();
            do{
                dados.add(new Object[]{
                    conex.res.getInt("catId"),
                    conex.res.getString("catNome"),
                    conex.res.getString("catDesc"),
                    conex.res.getString("catStatus")
                });
            }while(conex.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableCategoriaResult.setModel(tabela);
        jTableCategoriaResult.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableCategoriaResult.getColumnModel().getColumn(0).setResizable(false);
        jTableCategoriaResult.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableCategoriaResult.getColumnModel().getColumn(1).setResizable(false);
        jTableCategoriaResult.getColumnModel().getColumn(2).setPreferredWidth(350);
        jTableCategoriaResult.getColumnModel().getColumn(2).setResizable(false);
        jTableCategoriaResult.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableCategoriaResult.getColumnModel().getColumn(3).setResizable(false);
        jTableCategoriaResult.getTableHeader().setReorderingAllowed(false);
        jTableCategoriaResult.setAutoResizeMode(jTableCategoriaResult.AUTO_RESIZE_OFF);
        jTableCategoriaResult.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconetar();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadCategoriaCancelar;
    private javax.swing.JButton btnCadCategoriaEditar;
    private javax.swing.JButton btnCadCategoriaExcluir;
    private javax.swing.JButton btnCadCategoriaNovo;
    private javax.swing.JButton btnCadCategoriaPesquisar;
    private javax.swing.JButton btnCadCategoriaSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCategoriaResult;
    private javax.swing.JLabel lblCadUsuarioNome;
    private javax.swing.JLabel lblCadUsuarioNotas;
    private javax.swing.JLabel lblCatNaoActivo;
    private javax.swing.JLabel lblCategoriaStatus;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoName;
    private javax.swing.JPanel panelCadUserPesquisar;
    private javax.swing.JTextField txtCadCategoriaId;
    private javax.swing.JTextField txtCadCategoriaNome;
    private javax.swing.JTextArea txtCadCategoriaNotas;
    private javax.swing.JTextField txtCadCategoriaPesquisar;
    private javax.swing.JTextField txtCategoriaStatus;
    // End of variables declaration//GEN-END:variables
}
