/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import br.aiec.projetoFinal.conexao.ModuloConexao;
import br.aiec.projetoFinal.modelo.ModeloDepartamento;
import br.aiec.projetoFinal.controle.ControleDepartamento;
import br.aiec.projetoFinal.modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Zangui
 */
public class FrmDepartamentos extends javax.swing.JFrame {
    ModuloConexao conex = new ModuloConexao();
    ModuloConexao conexTb = new ModuloConexao();
    ModeloDepartamento dpto = new ModeloDepartamento();
    ControleDepartamento controle = new ControleDepartamento();
    
    int opcControl = 0;
    /**
     * Creates new form FrmDepartamentos
     */
    public FrmDepartamentos() {
        initComponents();
        listaDirectores();
        preencheTabela("SELECT departamentos.dptoNome,departamentos.dptoCod,usuarios.userNome,departamentos.dptoDesc FROM departamentos INNER JOIN usuarios ON usuarios.userId = departamentos.dptoDiret");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCadDepartamentoNovo = new javax.swing.JButton();
        btnCadDepartamentoSalvar = new javax.swing.JButton();
        btnCadDepartamentoEditar = new javax.swing.JButton();
        btnCadDepartamentoCancelar = new javax.swing.JButton();
        btnCadDepartamentoExcluir = new javax.swing.JButton();
        txtCadDepartamentoId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtCadDepartamentoNome = new javax.swing.JTextField();
        lblCadUsuarioNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboCadDepartamentoDiret = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCadDepartamentoCodigo = new javax.swing.JTextField();
        panelCadDepartamentoPesquisar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCadDepartamentoPesquisar = new javax.swing.JTextField();
        btnCadDepartamentoPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDepartamentoResult = new javax.swing.JTable();
        lblDptoNaoActivo = new javax.swing.JLabel();
        lblCategoriaStatus = new javax.swing.JLabel();
        txtDepartamentoStatus = new javax.swing.JTextField();
        lblCadUsuarioNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadDepartamentoNotas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Departamento");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_categorias_20x.png"))); // NOI18N

        lblLogoName.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblLogoName.setText("GESTARQ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("- Departamentos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoName)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5))
        );

        btnCadDepartamentoNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadDepartamentoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_novo_20x.png"))); // NOI18N
        btnCadDepartamentoNovo.setText("Novo");
        btnCadDepartamentoNovo.setToolTipText("Criar Novo Registo");
        btnCadDepartamentoNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadDepartamentoNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadDepartamentoNovo.setIconTextGap(10);
        btnCadDepartamentoNovo.setMaximumSize(new java.awt.Dimension(91, 35));
        btnCadDepartamentoNovo.setMinimumSize(new java.awt.Dimension(91, 35));
        btnCadDepartamentoNovo.setPreferredSize(new java.awt.Dimension(91, 35));
        btnCadDepartamentoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDepartamentoNovoActionPerformed(evt);
            }
        });

        btnCadDepartamentoSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadDepartamentoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_salvar_20x.png"))); // NOI18N
        btnCadDepartamentoSalvar.setText("Salvar");
        btnCadDepartamentoSalvar.setToolTipText("Salvar alterações");
        btnCadDepartamentoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadDepartamentoSalvar.setEnabled(false);
        btnCadDepartamentoSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadDepartamentoSalvar.setIconTextGap(10);
        btnCadDepartamentoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDepartamentoSalvarActionPerformed(evt);
            }
        });

        btnCadDepartamentoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_actualizar_20x.png"))); // NOI18N
        btnCadDepartamentoEditar.setText("Editar");
        btnCadDepartamentoEditar.setToolTipText("Editar Registo");
        btnCadDepartamentoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadDepartamentoEditar.setEnabled(false);
        btnCadDepartamentoEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadDepartamentoEditar.setIconTextGap(10);
        btnCadDepartamentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDepartamentoEditarActionPerformed(evt);
            }
        });

        btnCadDepartamentoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_cancelar_20x.png"))); // NOI18N
        btnCadDepartamentoCancelar.setText("Cancelar");
        btnCadDepartamentoCancelar.setToolTipText("Cancelar Operação");
        btnCadDepartamentoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadDepartamentoCancelar.setEnabled(false);
        btnCadDepartamentoCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadDepartamentoCancelar.setIconTextGap(10);
        btnCadDepartamentoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDepartamentoCancelarActionPerformed(evt);
            }
        });

        btnCadDepartamentoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_excluir_20x.png"))); // NOI18N
        btnCadDepartamentoExcluir.setText("Excluir");
        btnCadDepartamentoExcluir.setToolTipText("Excluir Registo");
        btnCadDepartamentoExcluir.setEnabled(false);
        btnCadDepartamentoExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadDepartamentoExcluir.setIconTextGap(10);
        btnCadDepartamentoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDepartamentoExcluirActionPerformed(evt);
            }
        });

        txtCadDepartamentoId.setEnabled(false);
        txtCadDepartamentoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadDepartamentoIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadDepartamentoNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadDepartamentoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadDepartamentoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(btnCadDepartamentoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadDepartamentoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtCadDepartamentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadDepartamentoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadDepartamentoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadDepartamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadDepartamentoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadDepartamentoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCadDepartamentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtCadDepartamentoNome.setBackground(new java.awt.Color(204, 204, 204));
        txtCadDepartamentoNome.setEnabled(false);

        lblCadUsuarioNome.setText("Nome *");

        jLabel1.setText("Director *");

        comboCadDepartamentoDiret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCadDepartamentoDiret.setEnabled(false);

        jLabel4.setText("Cádigo");

        txtCadDepartamentoCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCadDepartamentoCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCadUsuarioNome)
                    .addComponent(txtCadDepartamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCadDepartamentoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(comboCadDepartamentoDiret, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadUsuarioNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadDepartamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCadDepartamentoDiret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadDepartamentoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelCadDepartamentoPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Pesquisar Usuários");

        txtCadDepartamentoPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        txtCadDepartamentoPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadDepartamentoPesquisarKeyReleased(evt);
            }
        });

        btnCadDepartamentoPesquisar.setText("Pesquisar");
        btnCadDepartamentoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDepartamentoPesquisarActionPerformed(evt);
            }
        });

        jTableDepartamentoResult.setBackground(new java.awt.Color(204, 204, 204));
        jTableDepartamentoResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDepartamentoResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDepartamentoResultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDepartamentoResult);

        javax.swing.GroupLayout panelCadDepartamentoPesquisarLayout = new javax.swing.GroupLayout(panelCadDepartamentoPesquisar);
        panelCadDepartamentoPesquisar.setLayout(panelCadDepartamentoPesquisarLayout);
        panelCadDepartamentoPesquisarLayout.setHorizontalGroup(
            panelCadDepartamentoPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadDepartamentoPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadDepartamentoPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelCadDepartamentoPesquisarLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCadDepartamentoPesquisarLayout.createSequentialGroup()
                        .addComponent(txtCadDepartamentoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadDepartamentoPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCadDepartamentoPesquisarLayout.setVerticalGroup(
            panelCadDepartamentoPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadDepartamentoPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadDepartamentoPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadDepartamentoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadDepartamentoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblDptoNaoActivo.setText("Inactivo");

        lblCategoriaStatus.setText("Status");

        txtDepartamentoStatus.setEnabled(false);

        lblCadUsuarioNotas.setText("Informação adicional");

        txtCadDepartamentoNotas.setBackground(new java.awt.Color(204, 204, 204));
        txtCadDepartamentoNotas.setLineWrap(true);
        txtCadDepartamentoNotas.setRows(5);
        txtCadDepartamentoNotas.setEnabled(false);
        jScrollPane1.setViewportView(txtCadDepartamentoNotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCadDepartamentoPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoriaStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txtDepartamentoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDptoNaoActivo))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadUsuarioNotas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(33, 33, 33))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblCadUsuarioNotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCadDepartamentoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblCategoriaStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDptoNaoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(txtDepartamentoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1025, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Método para preencher Direcotres no formulário Departamentos
    public void listaDirectores(){
        conex.conexao();
        conex.executaSQL("SELECT * FROM usuarios WHERE userNivel = 'Director' ORDER BY userNome");
        try {
            conex.res.first();
            comboCadDepartamentoDiret.removeAllItems();
            do{
                comboCadDepartamentoDiret.addItem(conex.res.getString("userNome"));
            }while(conex.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar Directores"+e.getMessage());
        }
        conex.desconetar();
    }
    private void btnCadDepartamentoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDepartamentoNovoActionPerformed
        //Ao clicar no botão Novo, desbloqueia os campos inativos
        opcControl = 1;
        txtCadDepartamentoNome.setEnabled(true);
        txtCadDepartamentoNotas.setEnabled(true);
        txtCadDepartamentoCodigo.setEnabled(true);
        comboCadDepartamentoDiret.setEnabled(true);
        btnCadDepartamentoSalvar.setEnabled(true);
        btnCadDepartamentoCancelar.setEnabled(true);
        btnCadDepartamentoEditar.setEnabled(false);
        txtCadDepartamentoNome.setText("");
        txtCadDepartamentoCodigo.setText("");
        txtCadDepartamentoNotas.setText("");
    }//GEN-LAST:event_btnCadDepartamentoNovoActionPerformed

    private void btnCadDepartamentoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDepartamentoSalvarActionPerformed
        dpto.setNome(txtCadDepartamentoNome.getText());
        dpto.setCod(txtCadDepartamentoCodigo.getText());
        dpto.setNotas(txtCadDepartamentoNotas.getText());

        //Certifica que os campos obrigatórios não estão vazios
        if(txtCadDepartamentoNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome para prosseguir");
            txtCadDepartamentoNome.requestFocus();
        }else if(txtCadDepartamentoCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Código para prosseguir");
            txtCadDepartamentoCodigo.requestFocus();
        }else{
            if(opcControl == 1){
                //Grava efectivamente os dados no banco
                controle.gravarDepartamento(dpto);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT departamentos.dptoNome,departamentos.dptoCod,usuarios.userNome,departamentos.dptoDesc FROM departamentos INNER JOIN usuarios ON usuarios.userId = departamentos.dptoDiret");
            }else{
                dpto.setId(Integer.parseInt(txtCadDepartamentoId.getText()));
                controle.editarDepartamento(dpto);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT departamentos.dptoNome,departamentos.dptoCod,usuarios.userNome,departamentos.dptoDesc FROM departamentos INNER JOIN usuarios ON usuarios.userId = departamentos.dptoDiret");
            }
            //Após gravar limpa os campos para a próxima inserçao
            txtCadDepartamentoNome.setText("");
            txtCadDepartamentoNotas.setText("");

            //Torna os campos inativos novamente
            txtCadDepartamentoNome.setEnabled(false);
            txtCadDepartamentoNotas.setEnabled(false);
            btnCadDepartamentoSalvar.setEnabled(false);
            btnCadDepartamentoCancelar.setEnabled(false);
        }
    }//GEN-LAST:event_btnCadDepartamentoSalvarActionPerformed

    private void btnCadDepartamentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDepartamentoEditarActionPerformed
        // Habilita dos campos bloqueados
        opcControl = 2;
        txtCadDepartamentoNome.setEnabled(!false);
        txtCadDepartamentoNotas.setEnabled(!false);
        btnCadDepartamentoSalvar.setEnabled(!false);
        btnCadDepartamentoCancelar.setEnabled(true);
        btnCadDepartamentoEditar.setEnabled(false);
        comboCadDepartamentoDiret.setEnabled(true);
    }//GEN-LAST:event_btnCadDepartamentoEditarActionPerformed

    private void btnCadDepartamentoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDepartamentoCancelarActionPerformed
        // Cancelar
        txtCadDepartamentoNome.setEnabled(!true);
        txtCadDepartamentoNotas.setEnabled(!true);
        btnCadDepartamentoSalvar.setEnabled(!true);
        btnCadDepartamentoCancelar.setEnabled(!true);
        btnCadDepartamentoNovo.setEnabled(true);

        //Após cancelar limpa os campos para a próxima inserçao
        txtCadDepartamentoNome.setText("");
        txtCadDepartamentoNotas.setText("");
    }//GEN-LAST:event_btnCadDepartamentoCancelarActionPerformed

    private void btnCadDepartamentoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDepartamentoExcluirActionPerformed
        // Exclui uma categoria
        int alerta = 0;
        alerta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir este Departamento?");
        if(alerta == JOptionPane.YES_OPTION){
            dpto.setId(Integer.parseInt(txtCadDepartamentoId.getText()));
            controle.eliminarDepartamento(dpto);
        }
        //Após eliminar limpa os campos do formulário
        txtCadDepartamentoId.setText("");
        txtCadDepartamentoNome.setText("");
        txtCadDepartamentoNotas.setText("");
        txtCadDepartamentoPesquisar.setText("");
        //Habilita/desbilita alguns botões
        btnCadDepartamentoNovo.setEnabled(true);
        btnCadDepartamentoEditar.setEnabled(false);
        btnCadDepartamentoExcluir.setEnabled(false);
        //Actualiza a tabela que lista os usuarios cadastrados
        preencheTabela("SELECT departamentos.dptoNome,departamentos.dptoCod,usuarios.userNome,departamentos.dptoDesc FROM departamentos INNER JOIN usuarios ON usuarios.userId = departamentos.dptoDiret");
    }//GEN-LAST:event_btnCadDepartamentoExcluirActionPerformed

    private void txtCadDepartamentoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadDepartamentoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadDepartamentoIdActionPerformed

    private void txtCadDepartamentoPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadDepartamentoPesquisarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadDepartamentoPesquisarKeyReleased

    private void btnCadDepartamentoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDepartamentoPesquisarActionPerformed
        // Pesquisa Departamentos cadastrados no BD
        int stt = 1;
        dpto.setPesquisar(txtCadDepartamentoPesquisar.getText());
        ModeloDepartamento dept = controle.pesquisaDepartamento(dpto);
        txtCadDepartamentoId.setText(String.valueOf(dept.getId()));
        txtCadDepartamentoNome.setText(dept.getNome());
        txtCadDepartamentoCodigo.setText(dept.getCod());
        comboCadDepartamentoDiret.setSelectedItem(dept.getDirect());
        txtCadDepartamentoNotas.setText(dept.getNotas());

        if(txtDepartamentoStatus.getText().equals(stt)){
            lblDptoNaoActivo.setVisible(true);
        }else{
            lblDptoNaoActivo.setVisible(!true);
        }

        //Desabilita botões
        btnCadDepartamentoNovo.setEnabled(!false);
        btnCadDepartamentoEditar.setEnabled(true);
        btnCadDepartamentoExcluir.setEnabled(true);
    }//GEN-LAST:event_btnCadDepartamentoPesquisarActionPerformed

    private void jTableDepartamentoResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDepartamentoResultMouseClicked
        // Ao seleccionar um item na tabela redireciona para o registo correspondente
        int stt = 1;
        String dp = ""+jTableDepartamentoResult.getValueAt(jTableDepartamentoResult.getSelectedRow(), 1);
        conexTb.conexao();
        conexTb.executaSQL("SELECT * FROM departamentos WHERE dptoCod ='"+dp+"'");
        try {
            conexTb.res.first();
            txtCadDepartamentoId.setText(String.valueOf(conexTb.res.getInt("dptoId")));
            txtCadDepartamentoNome.setText(conexTb.res.getString("dptoNome"));
            txtCadDepartamentoCodigo.setText(conexTb.res.getString("dptoCod"));
            txtCadDepartamentoNotas.setText(conexTb.res.getString("dptoDesc"));
            ModuloConexao sellConex = new ModuloConexao();
            sellConex.conexao();
            sellConex.executaSQL("SELECT * FROM usuarios WHERE userId = '"+conexTb.res.getInt("dptoDiret")+"'");
            sellConex.res.first();
            comboCadDepartamentoDiret.setSelectedItem(sellConex.res.getString("userNome"));
            sellConex.desconetar();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: Não foi possível listar Departamentos \n"+ex.getLocalizedMessage());
        }
        conexTb.desconetar();
        btnCadDepartamentoEditar.setEnabled(true);
        btnCadDepartamentoExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableDepartamentoResultMouseClicked
//Métodompara preencher a tabela resultado da pesquisa
    public void preencheTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome","Códio","Director","Notas"};
        conex.conexao();
        conex.executaSQL(Sql);
        try {
            conex.res.first();
            do{
                dados.add(new Object[]{
                    conex.res.getString("dptoNome"),
                    conex.res.getString("dptoCod"),
                    conex.res.getString("userNome"),
                    conex.res.getString("dptoDesc")
                });
            }while(conex.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableDepartamentoResult.setModel(tabela);
        jTableDepartamentoResult.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableDepartamentoResult.getColumnModel().getColumn(0).setResizable(false);
        jTableDepartamentoResult.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableDepartamentoResult.getColumnModel().getColumn(1).setResizable(false);
        jTableDepartamentoResult.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableDepartamentoResult.getColumnModel().getColumn(2).setResizable(false);
        jTableDepartamentoResult.getColumnModel().getColumn(3).setPreferredWidth(240);
        jTableDepartamentoResult.getColumnModel().getColumn(3).setResizable(false);
        
        jTableDepartamentoResult.getTableHeader().setReorderingAllowed(false);
        jTableDepartamentoResult.setAutoResizeMode(jTableDepartamentoResult.AUTO_RESIZE_OFF);
        jTableDepartamentoResult.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconetar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDepartamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadDepartamentoCancelar;
    private javax.swing.JButton btnCadDepartamentoEditar;
    private javax.swing.JButton btnCadDepartamentoExcluir;
    private javax.swing.JButton btnCadDepartamentoNovo;
    private javax.swing.JButton btnCadDepartamentoPesquisar;
    private javax.swing.JButton btnCadDepartamentoSalvar;
    private javax.swing.JComboBox<String> comboCadDepartamentoDiret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDepartamentoResult;
    private javax.swing.JLabel lblCadUsuarioNome;
    private javax.swing.JLabel lblCadUsuarioNotas;
    private javax.swing.JLabel lblCategoriaStatus;
    private javax.swing.JLabel lblDptoNaoActivo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoName;
    private javax.swing.JPanel panelCadDepartamentoPesquisar;
    private javax.swing.JTextField txtCadDepartamentoCodigo;
    private javax.swing.JTextField txtCadDepartamentoId;
    private javax.swing.JTextField txtCadDepartamentoNome;
    private javax.swing.JTextArea txtCadDepartamentoNotas;
    private javax.swing.JTextField txtCadDepartamentoPesquisar;
    private javax.swing.JTextField txtDepartamentoStatus;
    // End of variables declaration//GEN-END:variables
}
