/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import br.aiec.projetoFinal.conexao.ModuloConexao;
import br.aiec.projetoFinal.controle.ControleRegisto;
import br.aiec.projetoFinal.modelo.ModeloRegisto;
import br.aiec.projetoFinal.modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Zangui
 */
public class FrmRegistos extends javax.swing.JFrame {
    ModuloConexao conex = new ModuloConexao();
    ModeloRegisto rec = new ModeloRegisto();
    ControleRegisto controle = new ControleRegisto();
    int opcControl = 0;
    /**
     * Creates new form FrmRegistos
     */
    public FrmRegistos() {
        initComponents();
        listaDepartamentos();
        listaCategorias();
        preencheTabela("SELECT registos.regCod,registos.regNome,categorias.catNome,departamentos.dptoNome,registos.regDataEmissao,registos.regRetencao,registos.regLocalizacao,registos.regUrl,usuarios.userNome FROM registos INNER JOIN categorias ON categorias.catId = registos.regCatId INNER JOIN departamentos ON departamentos.dptoId = registos.regDptoId INNER JOIN usuarios ON usuarios.userId = registos.regCadPor ORDER BY registos.regNome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadRegistoNovo = new javax.swing.JButton();
        btnCadRegistoSalvar = new javax.swing.JButton();
        btnCadRegistoEditar = new javax.swing.JButton();
        btnCadRegistoCancelar = new javax.swing.JButton();
        btnCadRegistoExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCadRegCod = new javax.swing.JLabel();
        lblCadRegCat = new javax.swing.JLabel();
        lblCadRegDepto = new javax.swing.JLabel();
        comboCadRegistoDepartamento = new javax.swing.JComboBox<>();
        comboCadRegistoCategoria = new javax.swing.JComboBox<>();
        txtCadRegistoCodigo = new javax.swing.JTextField();
        lblCadRegNome = new javax.swing.JLabel();
        txtCadRegistoNome = new javax.swing.JTextField();
        lblCadRegEmissao = new javax.swing.JLabel();
        lblRegCadSuporte = new javax.swing.JLabel();
        comboCadRegistoSuporte = new javax.swing.JComboBox<>();
        lblCadRegAcesso = new javax.swing.JLabel();
        comboCadRegistoNivelAcesso = new javax.swing.JComboBox<>();
        lblCadRegRetencao = new javax.swing.JLabel();
        comboCadRegistoRetencao = new javax.swing.JComboBox<>();
        lblCadRegLocalizacao = new javax.swing.JLabel();
        lblCadRegUrl = new javax.swing.JLabel();
        txtCadRegistoLocalizacao = new javax.swing.JTextField();
        txtCadRegistoUrl = new javax.swing.JTextField();
        txtCadRegistoEmissao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadRegistoNotas = new javax.swing.JTextArea();
        lblCadRegNotas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCadRegistoPesquisar = new javax.swing.JTextField();
        btnCadRegistoPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRegistosResult = new javax.swing.JTable();
        lblRegCadPor = new javax.swing.JLabel();
        txtCadRegistoId = new javax.swing.JTextField();
        lblCadRegistoPor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestarq - Gestão de Registos");
        setPreferredSize(new java.awt.Dimension(1009, 537));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(143, 352));

        btnCadRegistoNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadRegistoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_novo_20x.png"))); // NOI18N
        btnCadRegistoNovo.setText("Novo");
        btnCadRegistoNovo.setToolTipText("Criar Novo Registo");
        btnCadRegistoNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadRegistoNovo.setIconTextGap(10);
        btnCadRegistoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegistoNovoActionPerformed(evt);
            }
        });

        btnCadRegistoSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadRegistoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_salvar_20x.png"))); // NOI18N
        btnCadRegistoSalvar.setText("Salvar");
        btnCadRegistoSalvar.setToolTipText("Salvar alterações");
        btnCadRegistoSalvar.setEnabled(false);
        btnCadRegistoSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadRegistoSalvar.setIconTextGap(10);
        btnCadRegistoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegistoSalvarActionPerformed(evt);
            }
        });

        btnCadRegistoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_actualizar_20x.png"))); // NOI18N
        btnCadRegistoEditar.setText("Editar");
        btnCadRegistoEditar.setToolTipText("Editar Registo");
        btnCadRegistoEditar.setEnabled(false);
        btnCadRegistoEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadRegistoEditar.setIconTextGap(10);
        btnCadRegistoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegistoEditarActionPerformed(evt);
            }
        });

        btnCadRegistoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_cancelar_20x.png"))); // NOI18N
        btnCadRegistoCancelar.setText("Cancelar");
        btnCadRegistoCancelar.setToolTipText("Cancelar Operação");
        btnCadRegistoCancelar.setEnabled(false);
        btnCadRegistoCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadRegistoCancelar.setIconTextGap(10);
        btnCadRegistoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegistoCancelarActionPerformed(evt);
            }
        });

        btnCadRegistoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_excluir_20x.png"))); // NOI18N
        btnCadRegistoExcluir.setText("Excluir");
        btnCadRegistoExcluir.setToolTipText("Excluir Registo");
        btnCadRegistoExcluir.setEnabled(false);
        btnCadRegistoExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadRegistoExcluir.setIconTextGap(10);
        btnCadRegistoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegistoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadRegistoNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadRegistoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadRegistoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadRegistoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(btnCadRegistoExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadRegistoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCadRegistoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCadRegistoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCadRegistoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCadRegistoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCadRegCod.setText("Código *");

        lblCadRegCat.setText("Categoria *");

        lblCadRegDepto.setText("Departamento *");

        comboCadRegistoDepartamento.setBackground(new java.awt.Color(204, 204, 204));
        comboCadRegistoDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCadRegistoDepartamento.setEnabled(false);

        comboCadRegistoCategoria.setBackground(new java.awt.Color(204, 204, 204));
        comboCadRegistoCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCadRegistoCategoria.setEnabled(false);

        txtCadRegistoCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCadRegistoCodigo.setEnabled(false);

        lblCadRegNome.setText("Título do Registo *");

        txtCadRegistoNome.setBackground(new java.awt.Color(204, 204, 204));
        txtCadRegistoNome.setEnabled(false);
        txtCadRegistoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadRegistoNomeActionPerformed(evt);
            }
        });

        lblCadRegEmissao.setText("Data Emissão *");

        lblRegCadSuporte.setText("Suporte *");

        comboCadRegistoSuporte.setBackground(new java.awt.Color(204, 204, 204));
        comboCadRegistoSuporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Físico", "Electrónico" }));
        comboCadRegistoSuporte.setEnabled(false);

        lblCadRegAcesso.setText("Nível Acesso *");

        comboCadRegistoNivelAcesso.setBackground(new java.awt.Color(204, 204, 204));
        comboCadRegistoNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Público", "Restrito", "Confidencial" }));
        comboCadRegistoNivelAcesso.setEnabled(false);

        lblCadRegRetencao.setText("Retenção *");

        comboCadRegistoRetencao.setBackground(new java.awt.Color(204, 204, 204));
        comboCadRegistoRetencao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "5", "10" }));
        comboCadRegistoRetencao.setEnabled(false);

        lblCadRegLocalizacao.setText("Localização *");

        lblCadRegUrl.setText("Cópia Digital *");

        txtCadRegistoLocalizacao.setBackground(new java.awt.Color(204, 204, 204));
        txtCadRegistoLocalizacao.setEnabled(false);

        txtCadRegistoUrl.setBackground(new java.awt.Color(204, 204, 204));
        txtCadRegistoUrl.setEnabled(false);

        txtCadRegistoEmissao.setBackground(new java.awt.Color(204, 204, 204));
        try {
            txtCadRegistoEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadRegistoEmissao.setEnabled(false);

        jLabel3.setText("Anos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadRegCod)
                    .addComponent(txtCadRegistoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCadRegistoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadRegCat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCadRegDepto)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addComponent(comboCadRegistoDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(txtCadRegistoNome)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCadRegEmissao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCadRegistoLocalizacao)
                            .addComponent(lblCadRegLocalizacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadRegistoEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboCadRegistoSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblCadRegAcesso)
                                        .addGap(0, 51, Short.MAX_VALUE))
                                    .addComponent(comboCadRegistoNivelAcesso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCadRegRetencao)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(comboCadRegistoRetencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))
                                .addGap(9, 9, 9))
                            .addComponent(txtCadRegistoUrl)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblCadRegUrl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblRegCadSuporte)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCadRegNome)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadRegDepto)
                    .addComponent(lblCadRegCat)
                    .addComponent(lblCadRegCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCadRegistoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCadRegistoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadRegistoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCadRegNome)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCadRegistoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCadRegEmissao)
                                    .addComponent(lblCadRegRetencao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboCadRegistoRetencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCadRegistoEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCadRegAcesso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCadRegistoNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRegCadSuporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCadRegistoSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadRegLocalizacao)
                    .addComponent(lblCadRegUrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadRegistoLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadRegistoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_registos_20x.png"))); // NOI18N

        lblLogoName.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblLogoName.setText("GESTARQ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("- Registos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(829, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoName)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5))
        );

        jLabel1.setText("* Campos obrigatórios");

        txtCadRegistoNotas.setBackground(new java.awt.Color(204, 204, 204));
        txtCadRegistoNotas.setColumns(20);
        txtCadRegistoNotas.setRows(5);
        txtCadRegistoNotas.setWrapStyleWord(true);
        txtCadRegistoNotas.setEnabled(false);
        jScrollPane1.setViewportView(txtCadRegistoNotas);

        lblCadRegNotas.setText("Notas");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Pesquisar Registos");

        btnCadRegistoPesquisar.setText("Pesquisar");
        btnCadRegistoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegistoPesquisarActionPerformed(evt);
            }
        });

        jTableRegistosResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRegistosResult.setEnabled(false);
        jTableRegistosResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegistosResultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableRegistosResult);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCadRegistoPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadRegistoPesquisar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadRegistoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadRegistoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );

        lblRegCadPor.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblRegCadPor.setText("Registo cadastrado por:");

        txtCadRegistoId.setEnabled(false);
        txtCadRegistoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadRegistoIdActionPerformed(evt);
            }
        });

        lblCadRegistoPor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCadRegistoPor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadRegistoPor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCadRegNotas)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtCadRegistoId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblCadRegistoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblRegCadPor, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRegCadPor)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadRegistoPor)
                            .addComponent(txtCadRegistoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblCadRegNotas))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(1025, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Método para preencher Departamentos no formulário REgistos
    public void listaDepartamentos(){
        conex.conexao();
        conex.executaSQL("SELECT * FROM departamentos ORDER BY dptoNome");
        try {
            conex.res.first();
            comboCadRegistoDepartamento.removeAllItems();
            do{
              comboCadRegistoDepartamento.addItem(conex.res.getString("dptoNome"));
            }while(conex.res.next());                   
        } catch (SQLException ex) {
            //Logger.getLogger(FrmRegistos.class.getName()).log(Level.SEVERE, null, ex);
        }
        conex.desconetar();
    }
    //Método para preencher Categorias no formulário Registos
    public void listaCategorias(){
        conex.conexao();
        conex.executaSQL("SELECT * FROM categorias ORDER BY catNome");
        try {
            conex.res.first();
            comboCadRegistoCategoria.removeAllItems();
            do{
                comboCadRegistoCategoria.addItem(conex.res.getString("catNome"));
            }while(conex.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível selecionar o Nome da Categoria"+e.getMessage());
        }
        conex.desconetar();
    }
    private void txtCadRegistoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadRegistoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadRegistoNomeActionPerformed

    private void btnCadRegistoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegistoNovoActionPerformed
        // Desabilita campos e botões
        opcControl = 1;
        txtCadRegistoNome.setEnabled(true);
        txtCadRegistoCodigo.setEnabled(true);
        comboCadRegistoCategoria.setEnabled(true);
        comboCadRegistoDepartamento.setEnabled(true);
        txtCadRegistoEmissao.setEnabled(true);
        comboCadRegistoSuporte.setEnabled(true);
        comboCadRegistoNivelAcesso.setEnabled(true);
        comboCadRegistoRetencao.setEnabled(true);
        txtCadRegistoLocalizacao.setEnabled(true);
        txtCadRegistoUrl.setEnabled(true);
        txtCadRegistoNotas.setEnabled(true);
        btnCadRegistoSalvar.setEnabled(true);
        btnCadRegistoCancelar.setEnabled(true);
    }//GEN-LAST:event_btnCadRegistoNovoActionPerformed

    private void btnCadRegistoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegistoCancelarActionPerformed
        // Desabilita campos e botões
        txtCadRegistoNome.setEnabled(!true);
        txtCadRegistoCodigo.setEnabled(!true);
        comboCadRegistoCategoria.setEnabled(!true);
        comboCadRegistoDepartamento.setEnabled(!true);
        txtCadRegistoEmissao.setEnabled(!true);
        comboCadRegistoSuporte.setEnabled(!true);
        comboCadRegistoNivelAcesso.setEnabled(!true);
        comboCadRegistoRetencao.setEnabled(!true);
        txtCadRegistoLocalizacao.setEnabled(!true);
        txtCadRegistoUrl.setEnabled(!true);
        txtCadRegistoNotas.setEnabled(!true);
        btnCadRegistoSalvar.setEnabled(!true);
        btnCadRegistoCancelar.setEnabled(!true);
        
        txtCadRegistoNome.setText("");
        txtCadRegistoCodigo.setText("");
        txtCadRegistoEmissao.setText("");
        txtCadRegistoLocalizacao.setText("");
        txtCadRegistoUrl.setText("");
        txtCadRegistoNotas.setText("");
    }//GEN-LAST:event_btnCadRegistoCancelarActionPerformed

    private void btnCadRegistoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegistoSalvarActionPerformed
        // Grava os dados no Banco de dados
        rec.setCodigo(txtCadRegistoCodigo.getText());
        rec.setCategoria((String) comboCadRegistoCategoria.getSelectedItem());
        rec.setNome(txtCadRegistoNome.getText());
        rec.setDepartamento((String) comboCadRegistoDepartamento.getSelectedItem());
        rec.setDataEmissao(txtCadRegistoEmissao.getText());
        rec.setSecreto((String) comboCadRegistoNivelAcesso.getSelectedItem());
        rec.setRetencao((String) comboCadRegistoRetencao.getSelectedItem());
        rec.setSuporte(comboCadRegistoSuporte.getSelectedItem().toString());
        rec.setLocalizacao(txtCadRegistoLocalizacao.getText());
        rec.setUrl(txtCadRegistoUrl.getText());
        rec.setNotas(txtCadRegistoNotas.getText());
        
        //Certifica preenchiemento de campos obrigatórios
        if(txtCadRegistoCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o Código do Registo para prosseguir");
            txtCadRegistoCodigo.requestFocus();
        }else if(txtCadRegistoNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o Nome do Registo para prosseguir");
            txtCadRegistoNome.requestFocus();
        }else if(txtCadRegistoEmissao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite a Data de Emissão do Registo para prosseguir");
            txtCadRegistoEmissao.requestFocus();
        }else if(txtCadRegistoLocalizacao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe a Localização do Código do Registo para prosseguir");
            txtCadRegistoLocalizacao.requestFocus();
        }else if(txtCadRegistoUrl.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Caminho do Registo Digital para prosseguir");
            txtCadRegistoUrl.requestFocus();
        }else{
            if(opcControl == 1){
                //Grava efectivamente os dados no banco
                controle.gravarRegisto(rec);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT registos.regCod,registos.regNome,categorias.catNome,departamentos.dptoNome,registos.regDataEmissao,registos.regRetencao,registos.regLocalizacao,registos.regUrl,usuarios.userNome FROM registos INNER JOIN categorias ON categorias.catId = registos.regCatId INNER JOIN departamentos ON departamentos.dptoId = registos.regDptoId INNER JOIN usuarios ON usuarios.userId = registos.regCadPor ORDER BY registos.regNome");
            }else{
                rec.setId(Integer.parseInt(txtCadRegistoId.getText()));
                controle.editarRegisto(rec);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT registos.regCod,registos.regNome,categorias.catNome,departamentos.dptoNome,registos.regDataEmissao,registos.regRetencao,registos.regLocalizacao,registos.regUrl,usuarios.userNome FROM registos INNER JOIN categorias ON categorias.catId = registos.regCatId INNER JOIN departamentos ON departamentos.dptoId = registos.regDptoId INNER JOIN usuarios ON usuarios.userId = registos.regCadPor ORDER BY registos.regNome");
            }
            
        }
        //Após gravar limpa os campos
        // Desabilita campos e botões
        txtCadRegistoNome.setEnabled(!true);
        txtCadRegistoCodigo.setEnabled(!true);
        comboCadRegistoCategoria.setEnabled(!true);
        comboCadRegistoDepartamento.setEnabled(!true);
        txtCadRegistoEmissao.setEnabled(!true);
        comboCadRegistoSuporte.setEnabled(!true);
        comboCadRegistoNivelAcesso.setEnabled(!true);
        comboCadRegistoRetencao.setEnabled(!true);
        txtCadRegistoLocalizacao.setEnabled(!true);
        txtCadRegistoUrl.setEnabled(!true);
        txtCadRegistoNotas.setEnabled(!true);
        btnCadRegistoSalvar.setEnabled(!true);
        btnCadRegistoCancelar.setEnabled(!true); 
        btnCadRegistoExcluir.setEnabled(!true);
        txtCadRegistoNome.setText("");
        txtCadRegistoCodigo.setText("");
        txtCadRegistoEmissao.setText("");
        txtCadRegistoLocalizacao.setText("");
        txtCadRegistoUrl.setText("");
        txtCadRegistoNotas.setText("");
        
       
    }//GEN-LAST:event_btnCadRegistoSalvarActionPerformed

    private void txtCadRegistoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadRegistoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadRegistoIdActionPerformed

    private void jTableRegistosResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistosResultMouseClicked
        // Ao seleccionar um item na tabela redireciona para o registo correspondente
        
        String registo = ""+jTableRegistosResult.getValueAt(jTableRegistosResult.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSQL("SELECT * FROM registos WHERE regNome ='"+ registo +"'");
        try {
            conex.res.first();
            txtCadRegistoId.setText(String.valueOf(conex.res.getInt("regId")));
            txtCadRegistoCodigo.setText(conex.res.getString("regCod"));
            txtCadRegistoNome.setText(conex.res.getString("regNome"));
            txtCadRegistoEmissao.setText(conex.res.getString("regDataEmisso"));
            comboCadRegistoSuporte.setSelectedItem(conex.res.getString("regSuporte"));
            comboCadRegistoNivelAcesso.setSelectedItem(conex.res.getString("regSecreto"));
            comboCadRegistoRetencao.setSelectedItem(conex.res.getString("regRetencao"));
            txtCadRegistoLocalizacao.setText(conex.res.getString("regLocalizacao"));
            txtCadRegistoUrl.setText(conex.res.getString("regUrl"));
            txtCadRegistoNotas.setText(conex.res.getString("regNotas"));
            lblCadRegistoPor.setText(conex.res.getString("regCadPor"));
            //Seleciona o Nome da Categoria
            ModuloConexao sellConexCat = new ModuloConexao();
            sellConexCat.conexao();
            sellConexCat.executaSQL("SELECT * FROM categorias WHERE catId = '"+conex.res.getInt("regCatId")+"'");
            sellConexCat.res.first();
            comboCadRegistoCategoria.setSelectedItem(sellConexCat.res.getString("catNome"));         
            sellConexCat.desconetar();
            
            //Seleciona o Nome do Departamento
            ModuloConexao sellConex = new ModuloConexao();
            sellConex.conexao();
            sellConex.executaSQL("SELECT * FROM departamentos WHERE dptoId = '"+conex.res.getInt("userDptoId")+"'");
            sellConex.res.first();
            comboCadRegistoDepartamento.setSelectedItem(sellConex.res.getString("dptoNome"));
            sellConex.desconetar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        conex.desconetar();
        btnCadRegistoEditar.setEnabled(true);
        btnCadRegistoExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableRegistosResultMouseClicked

    private void btnCadRegistoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegistoPesquisarActionPerformed
        // Pesquisa usuários cadastrados no BD
        rec.setPesquisar(txtCadRegistoPesquisar.getText());
        ModeloRegisto reg = controle.pesquisaRegisto(rec);
        txtCadRegistoId.setText(String.valueOf(reg.getId()));
        txtCadRegistoCodigo.setText(reg.getCodigo());
        comboCadRegistoDepartamento.setSelectedItem(reg.getDepartamento());
        comboCadRegistoCategoria.setSelectedItem(reg.getCategoria());
        txtCadRegistoNome.setText(reg.getNome());
        txtCadRegistoEmissao.setText(reg.getDataEmissao());
        comboCadRegistoSuporte.setSelectedItem(reg.getSuporte());
        comboCadRegistoNivelAcesso.setSelectedItem(reg.getSecreto());
        comboCadRegistoRetencao.setSelectedItem(reg.getRetencao());
        txtCadRegistoLocalizacao.setText(reg.getLocalizacao());
        txtCadRegistoUrl.setText(reg.getUrl());                      
        txtCadRegistoNotas.setText(reg.getNotas());
        lblCadRegistoPor.setText(reg.getUserCad());
        //Desabilita botões
        btnCadRegistoNovo.setEnabled(!false);
        btnCadRegistoEditar.setEnabled(true);
        btnCadRegistoExcluir.setEnabled(true);
    }//GEN-LAST:event_btnCadRegistoPesquisarActionPerformed

    private void btnCadRegistoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegistoEditarActionPerformed
        // Ao ser clicado habilita todos os campos para editar o registo
        opcControl = 2;
        txtCadRegistoCodigo.setEnabled(!false);
        comboCadRegistoCategoria.setEnabled(!false);
        comboCadRegistoDepartamento.setEnabled(!false);
        txtCadRegistoNome.setEnabled(!false);
        txtCadRegistoEmissao.setEnabled(!false);
        comboCadRegistoSuporte.setEnabled(!false);
        comboCadRegistoRetencao.setEnabled(!false);
        comboCadRegistoNivelAcesso.setEnabled(!false);
        txtCadRegistoLocalizacao.setEnabled(!false);
        txtCadRegistoUrl.setEnabled(!false);
        txtCadRegistoNotas.setEnabled(true);
        btnCadRegistoSalvar.setEnabled(!false);
        btnCadRegistoCancelar.setEnabled(true);
        btnCadRegistoEditar.setEnabled(false);
    }//GEN-LAST:event_btnCadRegistoEditarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtCadRegistoId.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnCadRegistoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegistoExcluirActionPerformed
        // TODO add your handling code here:
        int alerta = 0;
        alerta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir este Registo?");
        if(alerta == JOptionPane.YES_OPTION){
            rec.setId(Integer.parseInt(txtCadRegistoId.getText()));
            controle.eliminarRegisto(rec);
        }
        //Após eliminar limpa os campos do formulário
        txtCadRegistoNome.setText("");
        txtCadRegistoCodigo.setText("");
        txtCadRegistoEmissao.setText("");
        txtCadRegistoLocalizacao.setText("");
        txtCadRegistoUrl.setText("");
        txtCadRegistoNotas.setText("");
        //Habilita/desbilita alguns botões
        btnCadRegistoNovo.setEnabled(true);
        btnCadRegistoEditar.setEnabled(false);
        btnCadRegistoExcluir.setEnabled(false);
        //Actualiza a tabela que lista os usuarios cadastrados
        preencheTabela("SELECT registos.regCod,registos.regNome,categorias.catNome,departamentos.dptoNome,registos.regDataEmissao,registos.regRetencao,registos.regLocalizacao,registos.regUrl,usuarios.userNome FROM registos INNER JOIN categorias ON categorias.catId = registos.regCatId INNER JOIN departamentos ON departamentos.dptoId = registos.regDptoId INNER JOIN usuarios ON usuarios.userId = registos.regCadPor ORDER BY registos.regNome");
    }//GEN-LAST:event_btnCadRegistoExcluirActionPerformed
//Métodompara preencher a tabela resultado da pesquisa
    public void preencheTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Categoria","Departamento","Emissão","Retenção","Localização","Caminho","Por"};
        ModuloConexao conexTb = new ModuloConexao();
        conexTb.conexao();
        conexTb.executaSQL(Sql);
        try {
            conexTb.res.first();
            do{
                dados.add(new Object[]{
                    conexTb.res.getString("regCod"),
                    conexTb.res.getString("regNome"),
                    conexTb.res.getString("catNome"),
                    conexTb.res.getString("dptoNome"),
                    conexTb.res.getString("regDataEmissao"),
                    conexTb.res.getString("regRetencao"),
                    conexTb.res.getString("regLocalizacao"),
                    conexTb.res.getString("regUrl"),
                    conexTb.res.getString("userNome")
                });
            }while(conexTb.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableRegistosResult.setModel(tabela);
        jTableRegistosResult.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableRegistosResult.getColumnModel().getColumn(0).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableRegistosResult.getColumnModel().getColumn(1).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableRegistosResult.getColumnModel().getColumn(2).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableRegistosResult.getColumnModel().getColumn(3).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableRegistosResult.getColumnModel().getColumn(4).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableRegistosResult.getColumnModel().getColumn(5).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(6).setPreferredWidth(65);
        jTableRegistosResult.getColumnModel().getColumn(6).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(7).setPreferredWidth(150);
        jTableRegistosResult.getColumnModel().getColumn(7).setResizable(false);
        jTableRegistosResult.getColumnModel().getColumn(8).setPreferredWidth(130);
        jTableRegistosResult.getColumnModel().getColumn(8).setResizable(false);
        jTableRegistosResult.getTableHeader().setReorderingAllowed(false);
        jTableRegistosResult.setAutoResizeMode(jTableRegistosResult.AUTO_RESIZE_OFF);
        jTableRegistosResult.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexTb.desconetar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadRegistoCancelar;
    private javax.swing.JButton btnCadRegistoEditar;
    private javax.swing.JButton btnCadRegistoExcluir;
    private javax.swing.JButton btnCadRegistoNovo;
    private javax.swing.JButton btnCadRegistoPesquisar;
    private javax.swing.JButton btnCadRegistoSalvar;
    private javax.swing.JComboBox<String> comboCadRegistoCategoria;
    private javax.swing.JComboBox<String> comboCadRegistoDepartamento;
    private javax.swing.JComboBox<String> comboCadRegistoNivelAcesso;
    private javax.swing.JComboBox<String> comboCadRegistoRetencao;
    private javax.swing.JComboBox<String> comboCadRegistoSuporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRegistosResult;
    private javax.swing.JLabel lblCadRegAcesso;
    private javax.swing.JLabel lblCadRegCat;
    private javax.swing.JLabel lblCadRegCod;
    private javax.swing.JLabel lblCadRegDepto;
    private javax.swing.JLabel lblCadRegEmissao;
    private javax.swing.JLabel lblCadRegLocalizacao;
    private javax.swing.JLabel lblCadRegNome;
    private javax.swing.JLabel lblCadRegNotas;
    private javax.swing.JLabel lblCadRegRetencao;
    private javax.swing.JLabel lblCadRegUrl;
    private javax.swing.JLabel lblCadRegistoPor;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoName;
    private javax.swing.JLabel lblRegCadPor;
    private javax.swing.JLabel lblRegCadSuporte;
    private javax.swing.JTextField txtCadRegistoCodigo;
    private javax.swing.JFormattedTextField txtCadRegistoEmissao;
    private javax.swing.JTextField txtCadRegistoId;
    private javax.swing.JTextField txtCadRegistoLocalizacao;
    private javax.swing.JTextField txtCadRegistoNome;
    private javax.swing.JTextArea txtCadRegistoNotas;
    private javax.swing.JTextField txtCadRegistoPesquisar;
    private javax.swing.JTextField txtCadRegistoUrl;
    // End of variables declaration//GEN-END:variables
}
