/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import br.aiec.projetoFinal.conexao.ModuloConexao;
import br.aiec.projetoFinal.modelo.ModeloTabela;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author pal009287
 */
public class FrmRegisRetencao extends javax.swing.JFrame {
    ModuloConexao conexTb = new ModuloConexao();
    Date data = new Date();
    SimpleDateFormat ano = new SimpleDateFormat("yyyy");
    int limite = Integer.parseInt(ano.format(data));
    /**
     * Creates new form FrmRegisRetencao
     */
    public FrmRegisRetencao() {
        initComponents();
        
        preencherTabela("SELECT registos.regCod,registos.regNome,categorias.catNome,departamentos.dptoNome,registos.regDataEmissao,registos.regRetencao,registos.regLocalizacao,registos.regUrl,usuarios.userNome FROM registos INNER JOIN categorias ON categorias.catId = registos.regCatId INNER JOIN departamentos ON departamentos.dptoId = registos.regDptoId INNER JOIN usuarios ON usuarios.userId = registos.regCadPor WHERE ("+limite+")- regAnoEmissao > regRetencao ORDER BY registos.regNome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegisRetencao = new javax.swing.JTable();
        btnBloquearRegistos = new javax.swing.JButton();
        btnEliminarRegistos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_registos_20x.png"))); // NOI18N

        lblLogoName.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblLogoName.setText("GESTARQ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("- Retenção dos Registos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(741, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoName)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5))
        );

        jTableRegisRetencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableRegisRetencao);

        btnBloquearRegistos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_locked_20x.png"))); // NOI18N
        btnBloquearRegistos.setText("Bloquear os Registos");
        btnBloquearRegistos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBloquearRegistos.setPreferredSize(new java.awt.Dimension(151, 35));

        btnEliminarRegistos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_excluir_20x.png"))); // NOI18N
        btnEliminarRegistos.setText("Eliminar os Registos");
        btnEliminarRegistos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarRegistos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminarRegistos.setPreferredSize(new java.awt.Dimension(127, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBloquearRegistos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarRegistos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBloquearRegistos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarRegistos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(1025, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Métodompara preencher a tabela resultado da pesquisa
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Categoria","Departamento","Emissão","Retenção","Localização","Caminho","Por"};
        
        conexTb.conexao();
        conexTb.executaSQL(Sql);
        try {
            conexTb.res.first();
            do{
                dados.add(new Object[]{
                    conexTb.res.getString("regCod"),
                    conexTb.res.getString("regNome"),
                    conexTb.res.getString("catNome"),
                    conexTb.res.getString("dptoNome"),
                    conexTb.res.getString("regDataEmissao"),
                    conexTb.res.getString("regRetencao"),
                    conexTb.res.getString("regLocalizacao"),
                    conexTb.res.getString("regUrl"),
                    conexTb.res.getString("userNome")
                });
            }while(conexTb.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableRegisRetencao.setModel(tabela);
        jTableRegisRetencao.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableRegisRetencao.getColumnModel().getColumn(0).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableRegisRetencao.getColumnModel().getColumn(1).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableRegisRetencao.getColumnModel().getColumn(2).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableRegisRetencao.getColumnModel().getColumn(3).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableRegisRetencao.getColumnModel().getColumn(4).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableRegisRetencao.getColumnModel().getColumn(5).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(6).setPreferredWidth(65);
        jTableRegisRetencao.getColumnModel().getColumn(6).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(7).setPreferredWidth(150);
        jTableRegisRetencao.getColumnModel().getColumn(7).setResizable(false);
        jTableRegisRetencao.getColumnModel().getColumn(8).setPreferredWidth(130);
        jTableRegisRetencao.getColumnModel().getColumn(8).setResizable(false);
        jTableRegisRetencao.getTableHeader().setReorderingAllowed(false);
        jTableRegisRetencao.setAutoResizeMode(jTableRegisRetencao.AUTO_RESIZE_OFF);
        jTableRegisRetencao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexTb.desconetar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegisRetencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegisRetencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegisRetencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegisRetencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegisRetencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloquearRegistos;
    private javax.swing.JButton btnEliminarRegistos;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRegisRetencao;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoName;
    // End of variables declaration//GEN-END:variables
}
