/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import br.aiec.projetoFinal.controle.ControleUsuario;
import br.aiec.projetoFinal.conexao.ModuloConexao;
import br.aiec.projetoFinal.modelo.ModeloTabela;
import br.aiec.projetoFinal.modelo.ModeloUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author Zangui
 */
public class FrmUsuarios extends javax.swing.JFrame {
    ModuloConexao conex = new ModuloConexao();
    ModeloUsuario user = new ModeloUsuario();
    ControleUsuario controle = new ControleUsuario();
    int opcControl = 0;
    
       /**
     * Creates new form FrmUsuario
     */
    public FrmUsuarios() {
        initComponents();
        listaDepartamentos();
        preencheTabela("SELECT userLogin, userNome, dptoNome, userNivel, userStatus, userCadNotas FROM usuarios INNER JOIN departamentos on userDptoId = dptoId ORDER BY userId DESC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCadUsuarioLogin = new javax.swing.JLabel();
        txtCadUsuarioLogin = new javax.swing.JTextField();
        lblCadUsuarioDepartamento = new javax.swing.JLabel();
        comboCadUsuarioDepartamento = new javax.swing.JComboBox<>();
        lblCadUsuarioNome = new javax.swing.JLabel();
        txtCadUsuarioNome = new javax.swing.JTextField();
        lblCadUsuarioEmail = new javax.swing.JLabel();
        txtCadUsuarioEmail = new javax.swing.JTextField();
        lblCadUsuarioSenha = new javax.swing.JLabel();
        txtCadUsuarioSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCadUsuarioConfirmaSenha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnCadUsuarioNovo = new javax.swing.JButton();
        btnCadUsuarioSalvar = new javax.swing.JButton();
        btnCadUsuarioEditar = new javax.swing.JButton();
        btnCadUsuarioCancelar = new javax.swing.JButton();
        btnCadUsuarioExcluir = new javax.swing.JButton();
        txtCadUsuarioId = new javax.swing.JTextField();
        panelCadUserPesquisar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCadUsuarioPesquisar = new javax.swing.JTextField();
        btnCadRegPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuariosResult = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadUsuarioNotas = new javax.swing.JTextArea();
        lblCadUsuarioNotas = new javax.swing.JLabel();
        comboCadUsuarioNivel = new javax.swing.JComboBox<>();
        txtCadUsuarioPerfil = new javax.swing.JLabel();
        lblCadUsuarioEstado = new javax.swing.JLabel();
        comboCadUsuarioStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GESTARQ - Gestão de Usuários");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCadUsuarioLogin.setText("Código *");

        txtCadUsuarioLogin.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioLogin.setEnabled(false);

        lblCadUsuarioDepartamento.setText("Departamento *");

        comboCadUsuarioDepartamento.setBackground(new java.awt.Color(204, 204, 255));
        comboCadUsuarioDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCadUsuarioDepartamento.setEnabled(false);
        comboCadUsuarioDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCadUsuarioDepartamentoActionPerformed(evt);
            }
        });

        lblCadUsuarioNome.setText("Nome *");

        txtCadUsuarioNome.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioNome.setEnabled(false);

        lblCadUsuarioEmail.setText("Email *");

        txtCadUsuarioEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioEmail.setEnabled(false);
        txtCadUsuarioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadUsuarioEmailActionPerformed(evt);
            }
        });

        lblCadUsuarioSenha.setText("Senha *");

        txtCadUsuarioSenha.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioSenha.setEnabled(false);

        jLabel4.setText("Confirmar Senha *");

        txtCadUsuarioConfirmaSenha.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioConfirmaSenha.setEnabled(false);
        txtCadUsuarioConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadUsuarioConfirmaSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCadUsuarioNome, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadUsuarioEmail)
                    .addComponent(txtCadUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadUsuarioDepartamento)
                    .addComponent(comboCadUsuarioDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCadUsuarioNome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadUsuarioLogin)
                    .addComponent(txtCadUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCadUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadUsuarioSenha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtCadUsuarioConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCadUsuarioLogin)
                        .addGap(3, 3, 3)
                        .addComponent(txtCadUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCadUsuarioNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadUsuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCadUsuarioEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadUsuarioSenha)
                            .addComponent(jLabel4))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCadUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadUsuarioConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCadUsuarioDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCadUsuarioDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadUsuarioNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadUsuarioNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_novo_20x.png"))); // NOI18N
        btnCadUsuarioNovo.setText("Novo");
        btnCadUsuarioNovo.setToolTipText("Criar Novo Registo");
        btnCadUsuarioNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadUsuarioNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadUsuarioNovo.setIconTextGap(10);
        btnCadUsuarioNovo.setMaximumSize(new java.awt.Dimension(91, 35));
        btnCadUsuarioNovo.setMinimumSize(new java.awt.Dimension(91, 35));
        btnCadUsuarioNovo.setPreferredSize(new java.awt.Dimension(91, 35));
        btnCadUsuarioNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioNovoActionPerformed(evt);
            }
        });

        btnCadUsuarioSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadUsuarioSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_salvar_20x.png"))); // NOI18N
        btnCadUsuarioSalvar.setText("Salvar");
        btnCadUsuarioSalvar.setToolTipText("Salvar alterações");
        btnCadUsuarioSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadUsuarioSalvar.setEnabled(false);
        btnCadUsuarioSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadUsuarioSalvar.setIconTextGap(10);
        btnCadUsuarioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioSalvarActionPerformed(evt);
            }
        });

        btnCadUsuarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_actualizar_20x.png"))); // NOI18N
        btnCadUsuarioEditar.setText("Editar");
        btnCadUsuarioEditar.setToolTipText("Editar Registo");
        btnCadUsuarioEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadUsuarioEditar.setEnabled(false);
        btnCadUsuarioEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadUsuarioEditar.setIconTextGap(10);
        btnCadUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioEditarActionPerformed(evt);
            }
        });

        btnCadUsuarioCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_cancelar_20x.png"))); // NOI18N
        btnCadUsuarioCancelar.setText("Cancelar");
        btnCadUsuarioCancelar.setToolTipText("Cancelar Operação");
        btnCadUsuarioCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadUsuarioCancelar.setEnabled(false);
        btnCadUsuarioCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadUsuarioCancelar.setIconTextGap(10);
        btnCadUsuarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioCancelarActionPerformed(evt);
            }
        });

        btnCadUsuarioExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_btn_excluir_20x.png"))); // NOI18N
        btnCadUsuarioExcluir.setText("Excluir");
        btnCadUsuarioExcluir.setToolTipText("Excluir Registo");
        btnCadUsuarioExcluir.setEnabled(false);
        btnCadUsuarioExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadUsuarioExcluir.setIconTextGap(10);
        btnCadUsuarioExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioExcluirActionPerformed(evt);
            }
        });

        txtCadUsuarioId.setEnabled(false);
        txtCadUsuarioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadUsuarioIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadUsuarioNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadUsuarioSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadUsuarioEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(btnCadUsuarioCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadUsuarioExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtCadUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadUsuarioNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadUsuarioSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadUsuarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadUsuarioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadUsuarioExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCadUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelCadUserPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Pesquisar Usuários");

        txtCadUsuarioPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadUsuarioPesquisarKeyReleased(evt);
            }
        });

        btnCadRegPesquisar.setText("Pesquisar");
        btnCadRegPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRegPesquisarActionPerformed(evt);
            }
        });

        jTableUsuariosResult.setBackground(new java.awt.Color(204, 204, 204));
        jTableUsuariosResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuariosResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosResultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuariosResult);

        javax.swing.GroupLayout panelCadUserPesquisarLayout = new javax.swing.GroupLayout(panelCadUserPesquisar);
        panelCadUserPesquisar.setLayout(panelCadUserPesquisarLayout);
        panelCadUserPesquisarLayout.setHorizontalGroup(
            panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                        .addComponent(txtCadUsuarioPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadRegPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCadUserPesquisarLayout.setVerticalGroup(
            panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadUserPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadUserPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadUsuarioPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadRegPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_usuarios_20x.png"))); // NOI18N

        lblLogoName.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblLogoName.setText("GESTARQ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("- Usuários");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoName)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5))
        );

        jLabel1.setText("* Campos obrigatórios");

        txtCadUsuarioNotas.setBackground(new java.awt.Color(204, 204, 204));
        txtCadUsuarioNotas.setLineWrap(true);
        txtCadUsuarioNotas.setRows(5);
        txtCadUsuarioNotas.setEnabled(false);
        jScrollPane1.setViewportView(txtCadUsuarioNotas);

        lblCadUsuarioNotas.setText("Informação adicional");

        comboCadUsuarioNivel.setBackground(new java.awt.Color(204, 204, 255));
        comboCadUsuarioNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Director", "Usuário" }));
        comboCadUsuarioNivel.setEnabled(false);

        txtCadUsuarioPerfil.setText("Perfil *");

        lblCadUsuarioEstado.setText("Status *");

        comboCadUsuarioStatus.setBackground(new java.awt.Color(204, 204, 255));
        comboCadUsuarioStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        comboCadUsuarioStatus.setEnabled(false);
        comboCadUsuarioStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCadUsuarioStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCadUsuarioNotas)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCadUsuarioPerfil)
                                            .addComponent(comboCadUsuarioNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCadUsuarioEstado)
                                            .addComponent(comboCadUsuarioStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addComponent(panelCadUserPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCadUsuarioEstado)
                                        .addGap(0, 0, 0)
                                        .addComponent(comboCadUsuarioStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCadUsuarioPerfil)
                                        .addGap(0, 0, 0)
                                        .addComponent(comboCadUsuarioNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addComponent(lblCadUsuarioNotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCadUserPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1025, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Método para preencher Departamentos no formulário Usuarios
    public void listaDepartamentos(){
        conex.conexao();
        conex.executaSQL("SELECT * FROM departamentos ORDER BY dptoNome");
        try {
            conex.res.first();
            comboCadUsuarioDepartamento.removeAllItems();
            do{
              comboCadUsuarioDepartamento.addItem(conex.res.getString("dptoNome"));
            }while(conex.res.next());                   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar os departamentos");
        }
        conex.desconetar();
    }
    private void txtCadUsuarioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadUsuarioEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadUsuarioEmailActionPerformed

    private void txtCadUsuarioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadUsuarioIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadUsuarioIdActionPerformed

    private void btnCadUsuarioNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioNovoActionPerformed
        //Ao clicar no botão Novo, desbloqueia os campos inativos
        opcControl = 1;
        txtCadUsuarioLogin.setEnabled(true);
        txtCadUsuarioSenha.setEnabled(true);
        txtCadUsuarioConfirmaSenha.setEnabled(true);
        txtCadUsuarioNome.setEnabled(true);
        txtCadUsuarioEmail.setEnabled(true);
        comboCadUsuarioDepartamento.setEnabled(true);
        comboCadUsuarioNivel.setEnabled(true);
        txtCadUsuarioNotas.setEnabled(true);
        comboCadUsuarioStatus.setEnabled(true);
        btnCadUsuarioSalvar.setEnabled(true);
        btnCadUsuarioCancelar.setEnabled(true);
        btnCadUsuarioEditar.setEnabled(false);
        txtCadUsuarioLogin.setText("");
        txtCadUsuarioSenha.setText("");
        txtCadUsuarioConfirmaSenha.setText("");
        txtCadUsuarioNome.setText("");
        txtCadUsuarioEmail.setText("");
        comboCadUsuarioDepartamento.setActionCommand("");
        comboCadUsuarioNivel.setActionCommand("");
        comboCadUsuarioStatus.setActionCommand("");
        txtCadUsuarioNotas.setText("");
    }//GEN-LAST:event_btnCadUsuarioNovoActionPerformed

    private void btnCadUsuarioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioSalvarActionPerformed
        //Verifica usuario no banco de dados
        //        modelo.setEmail(txtCadUsuarioEmail.getText());
        //        modelo.setLogin(txtCadUsuarioLogin.getText());
        //        controle.verificaUsuario(modelo);

        //Grava as informações no banco de dados
        //modelo.setCodigo(Integer.parseInt(txtCadUsuarioId.getText()));
        
        user.setLogin(txtCadUsuarioLogin.getText());
        user.setSenha(txtCadUsuarioSenha.getText());
        user.setNome(txtCadUsuarioNome.getText());
        user.setEmail(txtCadUsuarioEmail.getText());
        user.setDepartamento((String) comboCadUsuarioDepartamento.getSelectedItem());
        user.setNivel(comboCadUsuarioNivel.getSelectedItem().toString());
        user.setNotas(txtCadUsuarioNotas.getText());
        user.setStatus((String) comboCadUsuarioStatus.getSelectedItem());
        
        //Certifica que os campos obrigatórios não estão vazios
        if(txtCadUsuarioLogin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Código para prosseguir");
            txtCadUsuarioLogin.requestFocus();
        }else if(txtCadUsuarioSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Senha para prosseguir");
            txtCadUsuarioSenha.requestFocus();
        }else if(txtCadUsuarioConfirmaSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Confirme a Senha para prosseguir");
            txtCadUsuarioConfirmaSenha.requestFocus();
        }else if((txtCadUsuarioSenha.getText()) == null ? (txtCadUsuarioConfirmaSenha.getText()) != null : !(txtCadUsuarioSenha.getText()).equals(txtCadUsuarioConfirmaSenha.getText())){
            JOptionPane.showMessageDialog(null, "As Senhas não conferem. Digite novamente.");
            txtCadUsuarioSenha.requestFocus();
        }else if(txtCadUsuarioNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome para prosseguir");
            txtCadUsuarioNome.requestFocus();
        }else if(txtCadUsuarioEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Email para prosseguir");
            txtCadUsuarioEmail.requestFocus();
        }else{
            if(opcControl == 1){
                //Grava efectivamente os dados no banco
                controle.gravarUsuario(user);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT userLogin, userNome, dptoNome, userNivel, userStatus, userCadNotas FROM usuarios INNER JOIN departamentos on userDptoId = dptoId ORDER BY userId DESC");
            }else{
                user.setCodigo(Integer.parseInt(txtCadUsuarioId.getText()));
                controle.editarUsuario(user);
                //Actualiza a tabela que lista os usuarios cadastrados
                preencheTabela("SELECT userLogin, userNome, dptoNome, userNivel, userStatus, userCadNotas FROM usuarios INNER JOIN departamentos on userDptoId = dptoId ORDER BY userId DESC");
            }
            //Após gravar limpa os campos para a próxima inserçao
            txtCadUsuarioLogin.setText("");
            txtCadUsuarioSenha.setText("");
            txtCadUsuarioConfirmaSenha.setText("");
            txtCadUsuarioNome.setText("");
            txtCadUsuarioEmail.setText("");
            txtCadUsuarioNotas.setText("");

            //Torna os campos inativos novamente
            txtCadUsuarioLogin.setEnabled(false);
            txtCadUsuarioSenha.setEnabled(false);
            txtCadUsuarioConfirmaSenha.setEnabled(false);
            txtCadUsuarioNome.setEnabled(false);
            txtCadUsuarioEmail.setEnabled(false);
            comboCadUsuarioDepartamento.setEnabled(false);
            comboCadUsuarioNivel.setEnabled(false);
            comboCadUsuarioStatus.setEnabled(false);
            txtCadUsuarioNotas.setEnabled(false);
            btnCadUsuarioSalvar.setEnabled(false);
            btnCadUsuarioCancelar.setEnabled(false);
        }

    }//GEN-LAST:event_btnCadUsuarioSalvarActionPerformed

    private void btnCadUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioEditarActionPerformed
        // Habilita dos campos bloqueados
        opcControl = 2;
        txtCadUsuarioLogin.setEnabled(!false);
        txtCadUsuarioSenha.setEnabled(!false);
        txtCadUsuarioConfirmaSenha.setEnabled(!false);
        txtCadUsuarioNome.setEnabled(!false);
        txtCadUsuarioEmail.setEnabled(!false);
        comboCadUsuarioDepartamento.setEnabled(!false);
        comboCadUsuarioNivel.setEnabled(!false);
        comboCadUsuarioStatus.setEnabled(!false);
        txtCadUsuarioNotas.setEnabled(!false);
        btnCadUsuarioSalvar.setEnabled(!false);
        btnCadUsuarioCancelar.setEnabled(true);
        btnCadUsuarioEditar.setEnabled(false);
    }//GEN-LAST:event_btnCadUsuarioEditarActionPerformed

    private void btnCadUsuarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioCancelarActionPerformed
        // TODO add your handling code here:
        txtCadUsuarioLogin.setEnabled(!true);
        txtCadUsuarioSenha.setEnabled(!true);
        txtCadUsuarioConfirmaSenha.setEnabled(!true);
        txtCadUsuarioNome.setEnabled(!true);
        txtCadUsuarioEmail.setEnabled(!true);
        comboCadUsuarioDepartamento.setEnabled(!true);
        comboCadUsuarioNivel.setEnabled(!true);
        txtCadUsuarioNotas.setEnabled(!true);
        comboCadUsuarioStatus.setEnabled(false);
        btnCadUsuarioSalvar.setEnabled(!true);
        btnCadUsuarioCancelar.setEnabled(!true);
        btnCadUsuarioNovo.setEnabled(true);

        //Após cancelar limpa os campos para a próxima inserçao
        txtCadUsuarioLogin.setText("");
        txtCadUsuarioSenha.setText("");
        txtCadUsuarioNome.setText("");
        txtCadUsuarioEmail.setText("");
        txtCadUsuarioNotas.setText("");
    }//GEN-LAST:event_btnCadUsuarioCancelarActionPerformed

    private void btnCadUsuarioExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioExcluirActionPerformed
        // Exclui um usuário
        int alerta = 0;
        alerta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir este Usuário?");
        if(alerta == JOptionPane.YES_OPTION){
            user.setCodigo(Integer.parseInt(txtCadUsuarioId.getText()));
            controle.eliminaUsuario(user);
        }
        //Após eliminar limpa os campos do formulário
        txtCadUsuarioId.setText("");
        txtCadUsuarioLogin.setText("");
        txtCadUsuarioSenha.setText("");
        txtCadUsuarioNome.setText("");
        txtCadUsuarioEmail.setText("");
        txtCadUsuarioNotas.setText("");
        txtCadUsuarioPesquisar.setText("");
        //Habilita/desbilita alguns botões
        btnCadUsuarioNovo.setEnabled(true);
        btnCadUsuarioEditar.setEnabled(false);
        btnCadUsuarioExcluir.setEnabled(false);
        //Actualiza a tabela que lista os usuarios cadastrados
        preencheTabela("SELECT userLogin, userNome, dptoNome, userNivel, userStatus, userCadNotas FROM usuarios INNER JOIN departamentos on userDptoId = dptoId ORDER BY userId DESC");
    }//GEN-LAST:event_btnCadUsuarioExcluirActionPerformed

    private void btnCadRegPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRegPesquisarActionPerformed
        // Pesquisa usuários cadastrados no BD
        user.setPesquisar(txtCadUsuarioPesquisar.getText());
        ModeloUsuario usu = controle.pesquisaUsuario(user);
        txtCadUsuarioId.setText(String.valueOf(usu.getCodigo()));
        txtCadUsuarioLogin.setText(usu.getLogin());
        txtCadUsuarioSenha.setText(usu.getSenha());
        txtCadUsuarioNome.setText(usu.getNome());
        txtCadUsuarioEmail.setText(usu.getEmail());
        comboCadUsuarioDepartamento.setSelectedItem(usu.getDepartamento());
        comboCadUsuarioNivel.setSelectedItem(usu.getNivel());
        comboCadUsuarioStatus.setSelectedItem(usu.getStatus());
        txtCadUsuarioNotas.setText(usu.getNotas());
        //Desabilita botões
        btnCadUsuarioNovo.setEnabled(!false);
        btnCadUsuarioEditar.setEnabled(true);
        btnCadUsuarioExcluir.setEnabled(true);
    }//GEN-LAST:event_btnCadRegPesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtCadUsuarioId.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtCadUsuarioConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadUsuarioConfirmaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadUsuarioConfirmaSenhaActionPerformed

    private void jTableUsuariosResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosResultMouseClicked
        // Ao seleccionar um item na tabela redireciona para o registo correspondente
        
        String usuario = ""+jTableUsuariosResult.getValueAt(jTableUsuariosResult.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSQL("SELECT * FROM usuarios WHERE userNome ='"+usuario+"'");
        try {
            conex.res.first();
            txtCadUsuarioId.setText(String.valueOf(conex.res.getInt("userId")));
            txtCadUsuarioLogin.setText(conex.res.getString("userLogin"));
            txtCadUsuarioSenha.setText(conex.res.getString("userSenha"));
            txtCadUsuarioNome.setText(conex.res.getString("userNome"));
            txtCadUsuarioEmail.setText(conex.res.getString("userEmail"));
            comboCadUsuarioNivel.setSelectedItem(conex.res.getString("userNivel"));
            comboCadUsuarioStatus.setSelectedItem(conex.res.getString("userStatus"));
            txtCadUsuarioNotas.setText(conex.res.getString("userCadNotas"));
            ModuloConexao sellConex = new ModuloConexao();
            sellConex.conexao();
            sellConex.executaSQL("SELECT * FROM departamentos WHERE dptoId = '"+conex.res.getInt("userDptoId")+"'");
            sellConex.res.first();
            comboCadUsuarioDepartamento.setSelectedItem(sellConex.res.getString("dptoNome"));
            sellConex.desconetar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        conex.desconetar();
        btnCadUsuarioEditar.setEnabled(true);
        btnCadUsuarioExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableUsuariosResultMouseClicked

    private void comboCadUsuarioDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCadUsuarioDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCadUsuarioDepartamentoActionPerformed

    private void comboCadUsuarioStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCadUsuarioStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCadUsuarioStatusActionPerformed

    private void txtCadUsuarioPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadUsuarioPesquisarKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCadUsuarioPesquisarKeyReleased
    //Método para preencher a tabela resultado da pesquisa
    public void preencheTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Departamento","Perfil","Status","Notas"};
        conex.conexao();
        conex.executaSQL(Sql);
        try {
            conex.res.first();
            do{
                dados.add(new Object[]{
                    conex.res.getString("userLogin"),
                    conex.res.getString("userNome"),
                    conex.res.getString("dptoNome"),
                    conex.res.getString("userNivel"),
                    conex.res.getString("userStatus"),
                    conex.res.getString("userCadNotas")
                });
            }while(conex.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableUsuariosResult.setModel(tabela);
        jTableUsuariosResult.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableUsuariosResult.getColumnModel().getColumn(0).setResizable(false);
        jTableUsuariosResult.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableUsuariosResult.getColumnModel().getColumn(1).setResizable(false);
        jTableUsuariosResult.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTableUsuariosResult.getColumnModel().getColumn(2).setResizable(false);
        jTableUsuariosResult.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableUsuariosResult.getColumnModel().getColumn(3).setResizable(false);
        jTableUsuariosResult.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableUsuariosResult.getColumnModel().getColumn(4).setResizable(false);
        jTableUsuariosResult.getColumnModel().getColumn(5).setPreferredWidth(250);
        jTableUsuariosResult.getColumnModel().getColumn(5).setResizable(false);
        jTableUsuariosResult.getTableHeader().setReorderingAllowed(false);
        jTableUsuariosResult.setAutoResizeMode(jTableUsuariosResult.AUTO_RESIZE_OFF);
        jTableUsuariosResult.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconetar();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadRegPesquisar;
    private javax.swing.JButton btnCadUsuarioCancelar;
    private javax.swing.JButton btnCadUsuarioEditar;
    private javax.swing.JButton btnCadUsuarioExcluir;
    private javax.swing.JButton btnCadUsuarioNovo;
    private javax.swing.JButton btnCadUsuarioSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCadUsuarioDepartamento;
    private javax.swing.JComboBox<String> comboCadUsuarioNivel;
    private javax.swing.JComboBox<String> comboCadUsuarioStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUsuariosResult;
    private javax.swing.JLabel lblCadUsuarioDepartamento;
    private javax.swing.JLabel lblCadUsuarioEmail;
    private javax.swing.JLabel lblCadUsuarioEstado;
    private javax.swing.JLabel lblCadUsuarioLogin;
    private javax.swing.JLabel lblCadUsuarioNome;
    private javax.swing.JLabel lblCadUsuarioNotas;
    private javax.swing.JLabel lblCadUsuarioSenha;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoName;
    private javax.swing.JPanel panelCadUserPesquisar;
    private javax.swing.JTextField txtCadUsuarioConfirmaSenha;
    private javax.swing.JTextField txtCadUsuarioEmail;
    private javax.swing.JTextField txtCadUsuarioId;
    private javax.swing.JTextField txtCadUsuarioLogin;
    private javax.swing.JTextField txtCadUsuarioNome;
    private javax.swing.JTextArea txtCadUsuarioNotas;
    private javax.swing.JLabel txtCadUsuarioPerfil;
    private javax.swing.JTextField txtCadUsuarioPesquisar;
    private javax.swing.JTextField txtCadUsuarioSenha;
    // End of variables declaration//GEN-END:variables
}
