/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import br.aiec.projetoFinal.conexao.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author Zangui
 */
public class TelaEditaPerfil extends javax.swing.JFrame {
    ModuloConexao conex = new ModuloConexao();
    /**
     * Creates new form TelaAjuda
     */
    public TelaEditaPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuPainelPrincipal = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCastraRegistos = new javax.swing.JMenuItem();
        jMenuCadastraUsuarios = new javax.swing.JMenuItem();
        jMenuCadastraCategorias = new javax.swing.JMenuItem();
        jMenuCadastraDepartamentos = new javax.swing.JMenuItem();
        jMenuCadastraPlanosArquivo = new javax.swing.JMenuItem();
        jMenuCadastraTarefas = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuEditarPerfil = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");
        setResizable(false);

        jMenuPainelPrincipal.setText("Arquivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_home_20x.png"))); // NOI18N
        jMenuItem1.setText("Painel Principal");
        jMenuPainelPrincipal.add(jMenuItem1);

        jMenuPrincipal.add(jMenuPainelPrincipal);

        jMenuCadastro.setText("Cadastro");

        jMenuCastraRegistos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_registos_20x.png"))); // NOI18N
        jMenuCastraRegistos.setText("Novo Registo");
        jMenuCastraRegistos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCastraRegistosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCastraRegistos);

        jMenuCadastraUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_usuarios_20x.png"))); // NOI18N
        jMenuCadastraUsuarios.setText("Novo Usuário");
        jMenuCadastraUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraUsuarios);

        jMenuCadastraCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_categorias_20x.png"))); // NOI18N
        jMenuCadastraCategorias.setText("Nova Categoria");
        jMenuCadastraCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraCategoriasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraCategorias);

        jMenuCadastraDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_departamentos_20x.png"))); // NOI18N
        jMenuCadastraDepartamentos.setText("Nova Área");
        jMenuCadastraDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraDepartamentosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraDepartamentos);

        jMenuCadastraPlanosArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icone_planos_20x.png"))); // NOI18N
        jMenuCadastraPlanosArquivo.setText("Plano de Arquivo");
        jMenuCadastraPlanosArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraPlanosArquivoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraPlanosArquivo);

        jMenuCadastraTarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_tarefas_20x.png"))); // NOI18N
        jMenuCadastraTarefas.setText("Nova Tarefa");
        jMenuCadastraTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraTarefasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraTarefas);

        jMenuPrincipal.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");
        jMenuPrincipal.add(jMenuRelatorios);

        jMenuAjuda.setText("Ajuda");

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_info_20x.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSobre);

        jMenuPrincipal.add(jMenuAjuda);

        jMenuOpcoes.setText("Opções");

        jMenuEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_usuarios_20x.png"))); // NOI18N
        jMenuEditarPerfil.setText("Editar Perfil");
        jMenuEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarPerfilActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuEditarPerfil);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_right_20x.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuSair);

        jMenuPrincipal.add(jMenuOpcoes);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCastraRegistosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCastraRegistosActionPerformed
        // Exibe o Formulário de Registos
        FrmRegistos registos = new FrmRegistos();
        registos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCastraRegistosActionPerformed

    private void jMenuCadastraUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraUsuariosActionPerformed
        // Abre o formulario para cadastro de usuarios
        FrmUsuarios frmUsers = new FrmUsuarios();
        frmUsers.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraUsuariosActionPerformed

    private void jMenuCadastraCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraCategoriasActionPerformed
        // Exibe o Formulário Categorias
        FrmCategorias categorias = new FrmCategorias();
        categorias.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraCategoriasActionPerformed

    private void jMenuCadastraDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraDepartamentosActionPerformed
        // Abre o formulário para cadastro de Departamentos
        FrmDepartamentos departamentos = new FrmDepartamentos();
        departamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraDepartamentosActionPerformed

    private void jMenuCadastraPlanosArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraPlanosArquivoActionPerformed
        // Abre o Formulário para cadastro de Planos de Arquivo
        FrmPlanosArquivo planos = new FrmPlanosArquivo();
        planos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraPlanosArquivoActionPerformed

    private void jMenuCadastraTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraTarefasActionPerformed
        // Abre o Formulário para cadastro de Tarefas
        FrmTarefas tarefas = new FrmTarefas();
        tarefas.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraTarefasActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        // Exibe a Tela com informações sobre o sistema
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jMenuEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarPerfilActionPerformed
        // Exibe a Tela para editar o perfil do usuário logado no sistema
        TelaEditaPerfil perfil = new TelaEditaPerfil();
        perfil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEditarPerfilActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // Sair do Sistema, exibe uma caixa de diálogo para SIM ou NÃO
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair do Sistema?", "Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Sistema encerrado com suscesso!");
            conex.desconetar();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditaPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuItem jMenuCadastraCategorias;
    private javax.swing.JMenuItem jMenuCadastraDepartamentos;
    private javax.swing.JMenuItem jMenuCadastraPlanosArquivo;
    private javax.swing.JMenuItem jMenuCadastraTarefas;
    private javax.swing.JMenuItem jMenuCadastraUsuarios;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCastraRegistos;
    private javax.swing.JMenuItem jMenuEditarPerfil;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenu jMenuPainelPrincipal;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
