/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aiec.projetoFinal.visao;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import br.aiec.projetoFinal.conexao.ModuloConexao;
import br.aiec.projetoFinal.modelo.ModeloTabela;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Zangui
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ModuloConexao conecta = new ModuloConexao();
    FrmUsuarios telaUsuarios = new FrmUsuarios();
    FrmRegistos telaRegistos = new FrmRegistos();
    FrmCategorias telaCategorias = new FrmCategorias();
    FrmDepartamentos telaDepartamentos = new FrmDepartamentos();
    FrmTarefas telaTarefas = new FrmTarefas();
    FrmPlanosArquivo telaPlanos = new FrmPlanosArquivo();
    TelaSobre sobre = new TelaSobre();
    FrmRegisRetencao telaRegisRetencao = new FrmRegisRetencao();
    //private String usuarioLogado;
    /**
     * Creates new form TelaPrincipal
     * @param userLogado
     * @param userNivel
     * @param userId
     */
    public TelaPrincipal(String userLogado, String userNivel, String userId) {
        initComponents();
        lblUserLogadoId.setText(userId);
        lblNomeUserLogado.setText(userLogado);
        lblPerfilUserLogado.setText(userNivel);
        lblFooterUserLogado.setText(userLogado);
        
        conecta.conexao();
        preencheTabela("SELECT userLogin, userNome, dptoNome, userNivel, userStatus, userCadNotas FROM usuarios INNER JOIN departamentos on userDptoId = dptoId ORDER BY userId DESC");
        preencheTabelaDepartamentos("SELECT departamentos.dptoNome,departamentos.dptoCod,usuarios.userNome,departamentos.dptoDesc FROM departamentos INNER JOIN usuarios ON usuarios.userId = departamentos.dptoDiret");
        preencheTabelaCategorias("SELECT * FROM categorias ORDER BY catId DESC");
        preencheTabelaRegistos("SELECT registos.regCod,registos.regNome,categorias.catNome,departamentos.dptoNome,registos.regDataEmissao,registos.regRetencao,registos.regLocalizacao,registos.regUrl,usuarios.userNome FROM registos INNER JOIN categorias ON categorias.catId = registos.regCatId INNER JOIN departamentos ON departamentos.dptoId = registos.regDptoId INNER JOIN usuarios ON usuarios.userId = registos.regCadPor ORDER BY registos.regId");
    }

    public TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNomeUserLogado = new javax.swing.JLabel();
        lblPerfilUserLogado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelLateral = new javax.swing.JPanel();
        btnGoFrmRegistos = new javax.swing.JButton();
        btnGoFrmCategorias = new javax.swing.JButton();
        btnGoFrmUsuarios = new javax.swing.JButton();
        btnGoFrmDepartamentos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblIconSobre = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblHeaderSair = new javax.swing.JLabel();
        lblAlertaIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDashRegistos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDashCategorias = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDashUsuarios = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableDashDepartamentos = new javax.swing.JTable();
        lblUserLogadoId = new javax.swing.JLabel();
        lblCadTarefas = new javax.swing.JLabel();
        lblCadPlanosArquivo = new javax.swing.JLabel();
        jPanelAlertaBg = new javax.swing.JPanel();
        lblAlertaTxt = new javax.swing.JLabel();
        btnAlertaBtn = new javax.swing.JButton();
        jPanelAlertaTotais = new javax.swing.JPanel();
        lblAlertaTxt1 = new javax.swing.JLabel();
        lblDashTotalUsers = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDashTotalDeptos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDashTotalCats = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDashTotalRegs = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblFooterUserLogado = new javax.swing.JLabel();
        lblDataHoje = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCastraRegistos = new javax.swing.JMenuItem();
        jMenuCadastraUsuarios = new javax.swing.JMenuItem();
        jMenuCadastraCategorias = new javax.swing.JMenuItem();
        jMenuCadastraDepartamentos = new javax.swing.JMenuItem();
        jMenuCadastraPlanosArquivo = new javax.swing.JMenuItem();
        jMenuCadastraTarefas = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuEditarPerfil = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestarq - Painel Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 171, 193));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_archive_32x.png"))); // NOI18N

        lblLogoName.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblLogoName.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoName.setText("GESTARQ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("- Gestão de Registos Empresariais");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_user_24x.png"))); // NOI18N

        lblNomeUserLogado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNomeUserLogado.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeUserLogado.setText("Usuário Logado");

        lblPerfilUserLogado.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfilUserLogado.setText("Administrador");

        jLabel1.setText("[ ");

        jLabel4.setText("]");

        jLabel11.setText("Acesso 25");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogoName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUserLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerfilUserLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoName)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lblNomeUserLogado)
                    .addComponent(lblPerfilUserLogado)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(5, 5, 5))
        );

        jPanelLateral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(512, 304));

        btnGoFrmRegistos.setBackground(new java.awt.Color(153, 153, 153));
        btnGoFrmRegistos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoFrmRegistos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_registos.png"))); // NOI18N
        btnGoFrmRegistos.setText("REGISTOS");
        btnGoFrmRegistos.setToolTipText("Gestão de Registos");
        btnGoFrmRegistos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoFrmRegistos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoFrmRegistos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGoFrmRegistos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoFrmRegistosActionPerformed(evt);
            }
        });

        btnGoFrmCategorias.setBackground(new java.awt.Color(153, 153, 153));
        btnGoFrmCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoFrmCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_categorias.png"))); // NOI18N
        btnGoFrmCategorias.setText("CATEGORIAS");
        btnGoFrmCategorias.setToolTipText("Gestão de Categorias");
        btnGoFrmCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoFrmCategorias.setEnabled(false);
        btnGoFrmCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoFrmCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGoFrmCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoFrmCategoriasActionPerformed(evt);
            }
        });

        btnGoFrmUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        btnGoFrmUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoFrmUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_usuarios.png"))); // NOI18N
        btnGoFrmUsuarios.setText("USUÁRIOS");
        btnGoFrmUsuarios.setToolTipText("Gestão de Usuários");
        btnGoFrmUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoFrmUsuarios.setEnabled(false);
        btnGoFrmUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoFrmUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGoFrmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoFrmUsuariosActionPerformed(evt);
            }
        });

        btnGoFrmDepartamentos.setBackground(new java.awt.Color(153, 153, 153));
        btnGoFrmDepartamentos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoFrmDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_departamentos.png"))); // NOI18N
        btnGoFrmDepartamentos.setText("DEPARTAMENTOS");
        btnGoFrmDepartamentos.setToolTipText("Gestão de Departamentos");
        btnGoFrmDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoFrmDepartamentos.setEnabled(false);
        btnGoFrmDepartamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoFrmDepartamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGoFrmDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoFrmDepartamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLateralLayout.createSequentialGroup()
                        .addComponent(btnGoFrmRegistos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGoFrmUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLateralLayout.createSequentialGroup()
                        .addComponent(btnGoFrmCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoFrmDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGoFrmRegistos, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnGoFrmUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGoFrmCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnGoFrmDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIconSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_home_24x.png"))); // NOI18N
        lblIconSobre.setText("Sobre o Sistema");
        lblIconSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconSobreMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_settings_24x.png"))); // NOI18N
        jLabel9.setText("Configurações");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_help_24x.png"))); // NOI18N
        jLabel10.setText("Ajuda");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblHeaderSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_sair_24x.png"))); // NOI18N
        lblHeaderSair.setText("Sair");
        lblHeaderSair.setToolTipText("Sair do sistema");
        lblHeaderSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHeaderSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHeaderSairMouseClicked(evt);
            }
        });

        lblAlertaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_info_20x.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAlertaIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(lblIconSobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeaderSair)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblInfo)
                    .addComponent(lblIconSobre)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(lblHeaderSair)
                    .addComponent(lblAlertaIcon))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        jTableDashRegistos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDashRegistos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jTableDashRegistos);

        jTabbedPane1.addTab("Registos", jScrollPane2);

        jTableDashCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDashCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(jTableDashCategorias);

        jTabbedPane1.addTab("Categorias", jScrollPane3);

        jTableDashUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDashUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableDashUsuarios.setEnabled(false);
        jScrollPane4.setViewportView(jTableDashUsuarios);

        jTabbedPane1.addTab("Usuários", jScrollPane4);

        jTableDashDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDashDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane5.setViewportView(jTableDashDepartamentos);

        jTabbedPane1.addTab("Departamentos", jScrollPane5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        lblCadTarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_tarefas.png"))); // NOI18N
        lblCadTarefas.setText("Tarefas");
        lblCadTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadTarefasMouseClicked(evt);
            }
        });

        lblCadPlanosArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icone_planos.png"))); // NOI18N
        lblCadPlanosArquivo.setText("Planos de Arquivo");
        lblCadPlanosArquivo.setEnabled(false);
        lblCadPlanosArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadPlanosArquivoMouseClicked(evt);
            }
        });

        jPanelAlertaBg.setBackground(new java.awt.Color(255, 204, 51));

        lblAlertaTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAlertaTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_notificacao_20x.png"))); // NOI18N

        btnAlertaBtn.setText("Ver Registos");
        btnAlertaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlertaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlertaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlertaBgLayout = new javax.swing.GroupLayout(jPanelAlertaBg);
        jPanelAlertaBg.setLayout(jPanelAlertaBgLayout);
        jPanelAlertaBgLayout.setHorizontalGroup(
            jPanelAlertaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlertaBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlertaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAlertaBtn)
                .addContainerGap())
        );
        jPanelAlertaBgLayout.setVerticalGroup(
            jPanelAlertaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlertaBgLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelAlertaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlertaTxt)
                    .addComponent(btnAlertaBtn))
                .addGap(5, 5, 5))
        );

        lblAlertaTxt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_info_20x.png"))); // NOI18N
        lblAlertaTxt1.setText("Existem ");

        lblDashTotalUsers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDashTotalUsers.setText("8");

        jLabel3.setText("Usuários, ");

        lblDashTotalDeptos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDashTotalDeptos.setText("4");

        jLabel2.setText("Departamentos,");

        lblDashTotalCats.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDashTotalCats.setText("18");

        jLabel7.setText("Categorias, ");

        lblDashTotalRegs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDashTotalRegs.setText("158");

        jLabel8.setText("Registos");

        javax.swing.GroupLayout jPanelAlertaTotaisLayout = new javax.swing.GroupLayout(jPanelAlertaTotais);
        jPanelAlertaTotais.setLayout(jPanelAlertaTotaisLayout);
        jPanelAlertaTotaisLayout.setHorizontalGroup(
            jPanelAlertaTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlertaTotaisLayout.createSequentialGroup()
                .addComponent(lblAlertaTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashTotalUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashTotalDeptos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashTotalCats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashTotalRegs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanelAlertaTotaisLayout.setVerticalGroup(
            jPanelAlertaTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlertaTotaisLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelAlertaTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(lblDashTotalUsers)
                    .addComponent(lblAlertaTxt1)
                    .addComponent(lblDashTotalDeptos)
                    .addComponent(jLabel2)
                    .addComponent(lblDashTotalCats)
                    .addComponent(jLabel7)
                    .addComponent(lblDashTotalRegs)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFooterUserLogado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_user_20x.png"))); // NOI18N
        lblFooterUserLogado.setText("jLabel9");

        lblDataHoje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_calendar_24x.png"))); // NOI18N
        lblDataHoje.setText("jLabel9");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblFooterUserLogado)
                .addGap(382, 382, 382)
                .addComponent(lblDataHoje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblFooterUserLogado, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(lblDataHoje))
        );

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setEnabled(false);

        jMenuCastraRegistos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_registos_20x.png"))); // NOI18N
        jMenuCastraRegistos.setText("Registos");
        jMenuCastraRegistos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCastraRegistosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCastraRegistos);

        jMenuCadastraUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_usuarios_20x.png"))); // NOI18N
        jMenuCadastraUsuarios.setText("Usuários");
        jMenuCadastraUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraUsuarios);

        jMenuCadastraCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_categorias_20x.png"))); // NOI18N
        jMenuCadastraCategorias.setText("Categorias");
        jMenuCadastraCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraCategoriasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraCategorias);

        jMenuCadastraDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_departamentos_20x.png"))); // NOI18N
        jMenuCadastraDepartamentos.setText("Departamentos");
        jMenuCadastraDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraDepartamentosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraDepartamentos);

        jMenuCadastraPlanosArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icone_planos_20x.png"))); // NOI18N
        jMenuCadastraPlanosArquivo.setText("Plano de Arquivo");
        jMenuCadastraPlanosArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraPlanosArquivoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraPlanosArquivo);

        jMenuCadastraTarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_tarefas_20x.png"))); // NOI18N
        jMenuCadastraTarefas.setText("Tarefas");
        jMenuCadastraTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastraTarefasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastraTarefas);

        jMenuPrincipal.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");
        jMenuPrincipal.add(jMenuRelatorios);

        jMenuAjuda.setText("Ajuda");

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_info_20x.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSobre);

        jMenuPrincipal.add(jMenuAjuda);

        jMenuOpcoes.setText("Opções");

        jMenuEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_usuarios_20x.png"))); // NOI18N
        jMenuEditarPerfil.setText("Editar Perfil");
        jMenuEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarPerfilActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuEditarPerfil);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/aiec/projetoFinal/imagens/icon_right_20x.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuSair);

        jMenuPrincipal.add(jMenuOpcoes);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelAlertaTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelAlertaBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblUserLogadoId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCadTarefas)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCadPlanosArquivo)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelAlertaBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAlertaTotais, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCadPlanosArquivo)
                                    .addComponent(lblCadTarefas)
                                    .addComponent(lblUserLogadoId)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1119, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCastraRegistosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCastraRegistosActionPerformed
        // Exibe o Formul�rio de Registos
        if(telaRegistos == null){
            telaRegistos = new FrmRegistos();
            telaRegistos.setVisible(true);
        }else{
            telaRegistos.setVisible(true);
        }
    }//GEN-LAST:event_jMenuCastraRegistosActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        // Exibe a Tela com informa��es sobre o sistema
        if(sobre == null){
            sobre = new TelaSobre();
            sobre.setVisible(true);
        }else{
            sobre.setVisible(true);
        }
    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        

//Exibição da data actual sempre que se inicia a aplica��o
        Date data = new Date();
        DateFormat formataData = DateFormat.getDateInstance(DateFormat.FULL);
        SimpleDateFormat ano = new SimpleDateFormat("yyyy");
        //System.out.println(ano.format(data));
        lblDataHoje.setText(formataData.format(data));
        lblUserLogadoId.setVisible(false);
        
        conecta.conexao();
        //Total registos fara do prazo de retenção
        int limite = Integer.parseInt(ano.format(data));
        try {
            conecta.executaSQL("SELECT * FROM registos WHERE regRetencao < ("+ limite +" - regAnoEmissao)");
            int totalRegs = 0; 
            System.out.println(totalRegs);
            if(totalRegs == 0){
                lblAlertaTxt.setText("Não existem Registos fora do prazo de retenção.");
                btnAlertaBtn.setVisible(false);
            }else{
                while(conecta.res.next()) {
                    totalRegs++;
                }
                lblAlertaTxt.setText(totalRegs + " Registos já ultrapassaram o seu prazo de retenção.");
            }
            
            //String anoEmissao = conecta.res.getString("regDataEmissao");
            //String anoCompara = anoEmissao.substring(0, 4);
            //String prazoRetencao = conecta.res.getString("regRetencao");
            
            //int tempo = Integer.parseInt(anoCompara);
            //int limite = Integer.parseInt(ano.format(data));
            
            //int prazo = limite - tempo;
            
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Exibe total de Usuários
        try {
            conecta.executaSQL("SELECT * FROM usuarios");
            //conecta.res.next();
            int count = 0;   
            while(conecta.res.next()) {  
                count++;                
            }   
            lblDashTotalUsers.setText(Integer.toString(count));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //Exibe total de Registos
        try {
            conecta.executaSQL("SELECT * FROM registos");
            //conecta.res.next();
            int count = 0;   
            while(conecta.res.next()) {  
                count++;                
            }   
            lblDashTotalRegs.setText(Integer.toString(count));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //Exibe total de Departamentos
        try {
            conecta.executaSQL("SELECT * FROM departamentos");
            //conecta.res.next();
            int count = 0;   
            while(conecta.res.next()) {  
                count++;                
            }   
            lblDashTotalDeptos.setText(Integer.toString(count));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //Exibe total de Departamentos
        try {
            conecta.executaSQL("SELECT * FROM categorias");
            //conecta.res.next();
            int count = 0;   
            while(conecta.res.next()) {  
                count++;                
            }   
            lblDashTotalCats.setText(Integer.toString(count));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        conecta.desconetar();
    }//GEN-LAST:event_formWindowActivated

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // Sair do Sistema, exibe uma caixa de di�logo para SIM ou N�O
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair do Sistema?", "Aten��o",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Sistema encerrado com suscesso!");
            conecta.desconetar();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuCadastraUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraUsuariosActionPerformed
        // Abre o formulario para cadastro de usuarios
       if(telaUsuarios == null){
            telaUsuarios = new FrmUsuarios();
            telaUsuarios.setVisible(true);
        }else{
            telaUsuarios.setVisible(true);
        }
    }//GEN-LAST:event_jMenuCadastraUsuariosActionPerformed

    private void jMenuCadastraDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraDepartamentosActionPerformed
        // Abre o Formul�rio de departamentos
        if(telaDepartamentos == null){
            telaDepartamentos = new FrmDepartamentos();
            telaDepartamentos.setVisible(true);
        }else{
            telaDepartamentos.setVisible(true);
        }
    }//GEN-LAST:event_jMenuCadastraDepartamentosActionPerformed

    private void jMenuCadastraCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraCategoriasActionPerformed
        // Abre o Formul�rio de categorias
        if(telaCategorias == null){
            telaCategorias = new FrmCategorias();
            telaCategorias.setVisible(true);
        }else{
            telaCategorias.setVisible(true);
        }
    }//GEN-LAST:event_jMenuCadastraCategoriasActionPerformed

    private void jMenuCadastraPlanosArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraPlanosArquivoActionPerformed
        // Abre o Formul�rio para cadastro de Planos de Arquivo
        FrmPlanosArquivo planos = new FrmPlanosArquivo();
        planos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraPlanosArquivoActionPerformed

    private void jMenuCadastraTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastraTarefasActionPerformed
        // Abre o Formul�rio para cadastro de Tarefas
        FrmTarefas tarefas = new FrmTarefas();
        tarefas.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCadastraTarefasActionPerformed

    private void jMenuEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarPerfilActionPerformed
        // Exibe a Tela para editar o perfil do usu�rio logado no sistema
        TelaEditaPerfil perfil = new TelaEditaPerfil();
        perfil.setVisible(true);
       
    }//GEN-LAST:event_jMenuEditarPerfilActionPerformed

    private void lblIconSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconSobreMouseClicked
        // Exibe a Tela com informa��es sobre o sistema
        if(sobre == null){
            sobre = new TelaSobre();
            sobre.setVisible(true);
        }else{
            sobre.setVisible(true);
        }
    }//GEN-LAST:event_lblIconSobreMouseClicked

    private void btnGoFrmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoFrmUsuariosActionPerformed
        // Abre o Formul�rio para grst�o dos Usu�rios
        
        if(telaUsuarios == null){
            telaUsuarios = new FrmUsuarios();
            telaUsuarios.setVisible(true);
        }else{
            telaUsuarios.setVisible(true);
        }
    }//GEN-LAST:event_btnGoFrmUsuariosActionPerformed

    private void btnGoFrmRegistosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoFrmRegistosActionPerformed
        // Abre o Formul�rio para gest�o de registos
        if(telaRegistos == null){
            telaRegistos = new FrmRegistos();
            telaRegistos.setVisible(true);
        }else{
            telaRegistos.setVisible(true);
        }        
    }//GEN-LAST:event_btnGoFrmRegistosActionPerformed

    private void lblHeaderSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHeaderSairMouseClicked
        // Sair do Sistema, exibe uma caixa de di�logo para SIM ou N�O
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair do Sistema?", "Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Sistema encerrado com suscesso!");
            conecta.desconetar();
            System.exit(0);
        }
    }//GEN-LAST:event_lblHeaderSairMouseClicked

    private void btnGoFrmCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoFrmCategoriasActionPerformed
        // Abre o Formul�rio de categorias
        if(telaCategorias == null){
            telaCategorias = new FrmCategorias();
            telaCategorias.setVisible(true);
        }else{
            telaCategorias.setVisible(true);
        }
    }//GEN-LAST:event_btnGoFrmCategoriasActionPerformed

    private void btnGoFrmDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoFrmDepartamentosActionPerformed
        // Abre o Formul�rio de departamentos
        if(telaDepartamentos == null){
            telaDepartamentos = new FrmDepartamentos();
            telaDepartamentos.setVisible(true);
        }else{
            telaDepartamentos.setVisible(true);
        }
    }//GEN-LAST:event_btnGoFrmDepartamentosActionPerformed

    private void lblCadTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadTarefasMouseClicked
        // Abre o Formul�rio de Cadastro Tarefas
        if(telaTarefas == null){
            telaTarefas = new FrmTarefas();
            telaTarefas.setVisible(true);
        }else{
            telaTarefas.setVisible(true);
        }
    }//GEN-LAST:event_lblCadTarefasMouseClicked

    private void lblCadPlanosArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPlanosArquivoMouseClicked
        // Abre o Formul�rio de Cadastro Planos
        if(telaPlanos == null){
            telaPlanos = new FrmPlanosArquivo();
            telaPlanos.setVisible(true);
        }else{
            telaPlanos.setVisible(true);
        }
    }//GEN-LAST:event_lblCadPlanosArquivoMouseClicked

    private void btnAlertaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertaBtnActionPerformed
        // TODO add your handling code here:
        if(telaRegisRetencao == null){
            telaRegisRetencao = new FrmRegisRetencao();
            telaRegisRetencao.setVisible(true);
        }else{
            telaRegisRetencao.setVisible(true);
        }
    }//GEN-LAST:event_btnAlertaBtnActionPerformed

    //M�todo para preencher a tabela usuarios
    public void preencheTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Departamento","Perfil","Notas"};
        conecta.conexao();
        conecta.executaSQL(Sql);
        try {
            conecta.res.first();
            do{
                dados.add(new Object[]{
                    conecta.res.getString("userLogin"),
                    conecta.res.getString("userNome"),
                    conecta.res.getString("dptoNome"),
                    conecta.res.getString("userNivel"),
                    conecta.res.getString("userCadNotas")
                });
            }while(conecta.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableDashUsuarios.setModel(tabela);
        jTableDashUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableDashUsuarios.getColumnModel().getColumn(0).setResizable(false);
        jTableDashUsuarios.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableDashUsuarios.getColumnModel().getColumn(1).setResizable(false);
        jTableDashUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableDashUsuarios.getColumnModel().getColumn(2).setResizable(false);
        jTableDashUsuarios.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTableDashUsuarios.getColumnModel().getColumn(3).setResizable(false);
        jTableDashUsuarios.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTableDashUsuarios.getColumnModel().getColumn(4).setResizable(false);
        jTableDashUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableDashUsuarios.setAutoResizeMode(jTableDashUsuarios.AUTO_RESIZE_OFF);
        jTableDashUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecta.desconetar();
    }
    //M�todo para preencher a tabela Departamentos
    public void preencheTabelaDepartamentos(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome","Código","Director","Notas"};
        conecta.conexao();
        conecta.executaSQL(Sql);
        try {
            conecta.res.first();
            do{
                dados.add(new Object[]{
                    conecta.res.getString("dptoNome"),
                    conecta.res.getString("dptoCod"),
                    conecta.res.getString("userNome"),
                    conecta.res.getString("dptoDesc")
                });
            }while(conecta.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableDashDepartamentos.setModel(tabela);
        jTableDashDepartamentos.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableDashDepartamentos.getColumnModel().getColumn(0).setResizable(false);
        jTableDashDepartamentos.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableDashDepartamentos.getColumnModel().getColumn(1).setResizable(false);
        jTableDashDepartamentos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableDashDepartamentos.getColumnModel().getColumn(2).setResizable(false);
        jTableDashDepartamentos.getColumnModel().getColumn(3).setPreferredWidth(230);
        jTableDashDepartamentos.getColumnModel().getColumn(3).setResizable(false);
        
        jTableDashDepartamentos.getTableHeader().setReorderingAllowed(false);
        jTableDashDepartamentos.setAutoResizeMode(jTableDashDepartamentos.AUTO_RESIZE_OFF);
        jTableDashDepartamentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecta.desconetar();
    }
    //Metodo preencher tabela categorias
    public void preencheTabelaCategorias(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Notas"};
        conecta.conexao();
        conecta.executaSQL(Sql);
        try {
            conecta.res.first();
            do{
                dados.add(new Object[]{
                    conecta.res.getInt("catId"),
                    conecta.res.getString("catNome"),
                    conecta.res.getString("catDesc")
                });
            }while(conecta.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableDashCategorias.setModel(tabela);
        jTableDashCategorias.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableDashCategorias.getColumnModel().getColumn(0).setResizable(false);
        jTableDashCategorias.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableDashCategorias.getColumnModel().getColumn(1).setResizable(false);
        jTableDashCategorias.getColumnModel().getColumn(2).setPreferredWidth(340);
        jTableDashCategorias.getColumnModel().getColumn(2).setResizable(false);
        jTableDashCategorias.getTableHeader().setReorderingAllowed(false);
        jTableDashCategorias.setAutoResizeMode(jTableDashCategorias.AUTO_RESIZE_OFF);
        jTableDashCategorias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecta.desconetar();
    }
    //M�todompara preencher a tabela resultado da pesquisa
    public void preencheTabelaRegistos(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código","Nome","Categoria","Departamento","Emissão","Localiza��o"};
        conecta.conexao();
        conecta.executaSQL(Sql);
        try {
            conecta.res.first();
            do{
                dados.add(new Object[]{
                    conecta.res.getString("regCod"),
                    conecta.res.getString("regNome"),
                    conecta.res.getString("catNome"),
                    conecta.res.getString("dptoNome"),
                    conecta.res.getString("regDataEmissao"),
                    conecta.res.getString("regLocalizacao")
                });
            }while(conecta.res.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        ModeloTabela tabela = new ModeloTabela(dados, colunas);
        jTableDashRegistos.setModel(tabela);
        jTableDashRegistos.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableDashRegistos.getColumnModel().getColumn(0).setResizable(false);
        jTableDashRegistos.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableDashRegistos.getColumnModel().getColumn(1).setResizable(false);
        jTableDashRegistos.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableDashRegistos.getColumnModel().getColumn(2).setResizable(false);
        jTableDashRegistos.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableDashRegistos.getColumnModel().getColumn(3).setResizable(false);
        jTableDashRegistos.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableDashRegistos.getColumnModel().getColumn(4).setResizable(false);
        jTableDashRegistos.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableDashRegistos.getColumnModel().getColumn(5).setResizable(false);
        jTableDashRegistos.getTableHeader().setReorderingAllowed(false);
        jTableDashRegistos.setAutoResizeMode(jTableDashRegistos.AUTO_RESIZE_OFF);
        jTableDashRegistos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecta.desconetar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertaBtn;
    public static javax.swing.JButton btnGoFrmCategorias;
    public static javax.swing.JButton btnGoFrmDepartamentos;
    private javax.swing.JButton btnGoFrmRegistos;
    public static javax.swing.JButton btnGoFrmUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuItem jMenuCadastraCategorias;
    private javax.swing.JMenuItem jMenuCadastraDepartamentos;
    private javax.swing.JMenuItem jMenuCadastraPlanosArquivo;
    private javax.swing.JMenuItem jMenuCadastraTarefas;
    private javax.swing.JMenuItem jMenuCadastraUsuarios;
    public static javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCastraRegistos;
    private javax.swing.JMenuItem jMenuEditarPerfil;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAlertaBg;
    private javax.swing.JPanel jPanelAlertaTotais;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDashCategorias;
    private javax.swing.JTable jTableDashDepartamentos;
    private javax.swing.JTable jTableDashRegistos;
    public static javax.swing.JTable jTableDashUsuarios;
    public static javax.swing.JLabel lblAlertaIcon;
    private javax.swing.JLabel lblAlertaTxt;
    private javax.swing.JLabel lblAlertaTxt1;
    public static javax.swing.JLabel lblCadPlanosArquivo;
    private javax.swing.JLabel lblCadTarefas;
    private javax.swing.JLabel lblDashTotalCats;
    private javax.swing.JLabel lblDashTotalDeptos;
    private javax.swing.JLabel lblDashTotalRegs;
    private javax.swing.JLabel lblDashTotalUsers;
    private javax.swing.JLabel lblDataHoje;
    private javax.swing.JLabel lblFooterUserLogado;
    private javax.swing.JLabel lblHeaderSair;
    private javax.swing.JLabel lblIconSobre;
    public static javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoName;
    public static javax.swing.JLabel lblNomeUserLogado;
    private javax.swing.JLabel lblPerfilUserLogado;
    public static javax.swing.JLabel lblUserLogadoId;
    // End of variables declaration//GEN-END:variables
}
